// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForCreateAdjustmentRecords implements pgx.CopyFromSource.
type iteratorForCreateAdjustmentRecords struct {
	rows                 []CreateAdjustmentRecordsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAdjustmentRecords) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAdjustmentRecords) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RunID,
		r.rows[0].ProjectID,
		r.rows[0].RelationID,
		r.rows[0].RelationType,
		r.rows[0].RelationTarget,
		r.rows[0].Beneficiary,
		r.rows[0].Type,
		r.rows[0].Scope,
		r.rows[0].Rate,
		r.rows[0].Base,
		r.rows[0].Amount,
		r.rows[0].Currency,
	}, nil
}

func (r iteratorForCreateAdjustmentRecords) Err() error {
	return nil
}

// The adjustment rows of a run, over the same protocol and naming id for the
// same reason: COPY evaluates no defaults.
func (q *Queries) CreateAdjustmentRecords(ctx context.Context, arg []CreateAdjustmentRecordsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"adjustment_records"}, []string{"id", "run_id", "project_id", "relation_id", "relation_type", "relation_target", "beneficiary", "type", "scope", "rate", "base", "amount", "currency"}, &iteratorForCreateAdjustmentRecords{rows: arg})
}

// iteratorForCreateCorrectionDeltas implements pgx.CopyFromSource.
type iteratorForCreateCorrectionDeltas struct {
	rows                 []CreateCorrectionDeltasParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCorrectionDeltas) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCorrectionDeltas) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RunID,
		r.rows[0].CorrectsRunID,
		r.rows[0].Cloud,
		r.rows[0].Platform,
		r.rows[0].ResourceType,
		r.rows[0].ResourceID,
		r.rows[0].ProjectID,
		r.rows[0].Dimension,
		r.rows[0].OldAmount,
		r.rows[0].NewAmount,
		r.rows[0].Delta,
		r.rows[0].Currency,
	}, nil
}

func (r iteratorForCreateCorrectionDeltas) Err() error {
	return nil
}

func (q *Queries) CreateCorrectionDeltas(ctx context.Context, arg []CreateCorrectionDeltasParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"correction_deltas"}, []string{"id", "run_id", "corrects_run_id", "cloud", "platform", "resource_type", "resource_id", "project_id", "dimension", "old_amount", "new_amount", "delta", "currency"}, &iteratorForCreateCorrectionDeltas{rows: arg})
}

// iteratorForCreateRatedRecords implements pgx.CopyFromSource.
type iteratorForCreateRatedRecords struct {
	rows                 []CreateRatedRecordsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRatedRecords) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRatedRecords) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RunID,
		r.rows[0].UsageRecordID,
		r.rows[0].Dimension,
		r.rows[0].Amount,
		r.rows[0].Currency,
	}, nil
}

func (r iteratorForCreateRatedRecords) Err() error {
	return nil
}

func (q *Queries) CreateRatedRecords(ctx context.Context, arg []CreateRatedRecordsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"rated_records"}, []string{"id", "run_id", "usage_record_id", "dimension", "amount", "currency"}, &iteratorForCreateRatedRecords{rows: arg})
}

// iteratorForCreateUsageRecords implements pgx.CopyFromSource.
type iteratorForCreateUsageRecords struct {
	rows                 []CreateUsageRecordsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateUsageRecords) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateUsageRecords) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RunID,
		r.rows[0].Cloud,
		r.rows[0].Platform,
		r.rows[0].ResourceType,
		r.rows[0].ResourceID,
		r.rows[0].ProjectID,
		r.rows[0].State,
		r.rows[0].FromTs,
		r.rows[0].ToTs,
		r.rows[0].Seconds,
		r.rows[0].Usage,
	}, nil
}

func (r iteratorForCreateUsageRecords) Err() error {
	return nil
}

// The record writes of a run, over the COPY protocol: a month of metering is
// tens of thousands of rows, and one round trip per row is what that costs.
// All three name id rather than leaving it to the column default, because COPY
// evaluates no defaults. The caller generating the ids is also what lets a
// rated record name the usage record it was rated from before either row is
// written.
func (q *Queries) CreateUsageRecords(ctx context.Context, arg []CreateUsageRecordsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"usage_records"}, []string{"id", "run_id", "cloud", "platform", "resource_type", "resource_id", "project_id", "state", "from_ts", "to_ts", "seconds", "usage"}, &iteratorForCreateUsageRecords{rows: arg})
}
