// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBillingPeriods = `-- name: ListBillingPeriods :many
SELECT period_from, status, finalized_run_id, finalized_at
FROM billing_periods
ORDER BY period_from
`

type ListBillingPeriodsRow struct {
	PeriodFrom     pgtype.Timestamptz
	Status         string
	FinalizedRunID pgtype.UUID
	FinalizedAt    pgtype.Timestamptz
}

func (q *Queries) ListBillingPeriods(ctx context.Context) ([]ListBillingPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listBillingPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillingPeriodsRow
	for rows.Next() {
		var i ListBillingPeriodsRow
		if err := rows.Scan(
			&i.PeriodFrom,
			&i.Status,
			&i.FinalizedRunID,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
