// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRun = `-- name: CompleteRun :execrows
UPDATE runs
SET status = 'completed', completed_at = now(), stats = $2
WHERE id = $1 AND status = 'running'
`

type CompleteRunParams struct {
	ID    pgtype.UUID
	Stats []byte
}

// The three ends of a run. stats carries what the run counted, and the failed
// one keeps it: a run that broke halfway is read for how far it got.
//
// The two ends of a run in flight name the status they move from and report how
// many rows they moved. A run this process opened can have been failed
// underneath it by the reclaim below, and putting it back would return a run
// the period has already replaced to that period's numbers: trg_runs_immutable
// fires on OLD.status = 'finalized' alone, so 'failed' -> 'completed' passes the
// database untouched. The caller reads the count and refuses rather than
// writing over a status another process settled.
func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRun, arg.ID, arg.Stats)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consecutiveFailedRuns = `-- name: ConsecutiveFailedRuns :one
WITH last_success AS (
    SELECT coalesce(max(started_at), '-infinity'::timestamptz) AS started_at
    FROM runs
    WHERE period_from = $1 AND kind = 'regular'
      AND status IN ('completed', 'finalized', 'superseded')
)
SELECT count(*)::int AS failures, max(runs.completed_at)::timestamptz AS last_failure
FROM runs, last_success
WHERE runs.period_from = $1 AND runs.kind = 'regular' AND runs.status = 'failed'
  AND runs.started_at > last_success.started_at
`

type ConsecutiveFailedRunsRow struct {
	Failures    int32
	LastFailure pgtype.Timestamptz
}

// How often the metering of a period failed in a row: the failed regular runs it
// carries since the last one that got to the end, and when the last of them
// stopped. Without this the tick meters a month again on every hourly pass for
// as long as it keeps failing, and a month that never stops failing -- an event
// ordering its history carries and no later event repairs -- costs a full
// metering pass and another stats blob every hour for the life of the
// deployment. The scheduler spaces its retries out over this count.
func (q *Queries) ConsecutiveFailedRuns(ctx context.Context, periodFrom pgtype.Timestamptz) (ConsecutiveFailedRunsRow, error) {
	row := q.db.QueryRow(ctx, consecutiveFailedRuns, periodFrom)
	var i ConsecutiveFailedRunsRow
	err := row.Scan(&i.Failures, &i.LastFailure)
	return i, err
}

type CreateAdjustmentRecordsParams struct {
	ID             pgtype.UUID
	RunID          pgtype.UUID
	ProjectID      string
	RelationID     pgtype.UUID
	RelationType   string
	RelationTarget string
	Beneficiary    pgtype.Text
	Type           string
	Scope          string
	Rate           pgtype.Numeric
	Base           pgtype.Numeric
	Amount         pgtype.Numeric
	Currency       string
}

type CreateCorrectionDeltasParams struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	CorrectsRunID pgtype.UUID
	Cloud         string
	Platform      string
	ResourceType  string
	ResourceID    string
	ProjectID     string
	Dimension     string
	OldAmount     pgtype.Numeric
	NewAmount     pgtype.Numeric
	Delta         pgtype.Numeric
	Currency      string
}

type CreateRatedRecordsParams struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	UsageRecordID pgtype.UUID
	Dimension     string
	Amount        pgtype.Numeric
	Currency      string
}

type CreateUsageRecordsParams struct {
	ID           pgtype.UUID
	RunID        pgtype.UUID
	Cloud        string
	Platform     string
	ResourceType string
	ResourceID   string
	ProjectID    string
	State        string
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
	Seconds      int64
	Usage        []byte
}

const earliestBillingPeriod = `-- name: EarliestBillingPeriod :one
SELECT min(period_from)::timestamptz FROM billing_periods
`

// The first period the engine knows, where the scheduler starts its walk. The
// aggregate answers over an empty table too, with one NULL row.
func (q *Queries) EarliestBillingPeriod(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, earliestBillingPeriod)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const failRun = `-- name: FailRun :execrows
UPDATE runs
SET status = 'failed', completed_at = now(), stats = $2
WHERE id = $1 AND status = 'running'
`

type FailRunParams struct {
	ID    pgtype.UUID
	Stats []byte
}

func (q *Queries) FailRun(ctx context.Context, arg FailRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, failRun, arg.ID, arg.Stats)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeBillingPeriod = `-- name: FinalizeBillingPeriod :exec
UPDATE billing_periods
SET status = 'finalized', finalized_run_id = $2, finalized_at = now()
WHERE period_from = $1
`

type FinalizeBillingPeriodParams struct {
	PeriodFrom     pgtype.Timestamptz
	FinalizedRunID pgtype.UUID
}

// Closes a period. The three columns move in one statement because the check
// constraint on billing_periods ties them together: a period is finalized
// exactly when it names the run that closed it and the time that happened.
func (q *Queries) FinalizeBillingPeriod(ctx context.Context, arg FinalizeBillingPeriodParams) error {
	_, err := q.db.Exec(ctx, finalizeBillingPeriod, arg.PeriodFrom, arg.FinalizedRunID)
	return err
}

const finalizeRun = `-- name: FinalizeRun :exec
UPDATE runs
SET status = 'finalized'
WHERE id = $1
`

func (q *Queries) FinalizeRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finalizeRun, id)
	return err
}

const getBillingPeriod = `-- name: GetBillingPeriod :one
SELECT period_from, period_to, status, finalized_run_id, finalized_at
FROM billing_periods
WHERE period_from = $1
`

func (q *Queries) GetBillingPeriod(ctx context.Context, periodFrom pgtype.Timestamptz) (BillingPeriod, error) {
	row := q.db.QueryRow(ctx, getBillingPeriod, periodFrom)
	var i BillingPeriod
	err := row.Scan(
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Status,
		&i.FinalizedRunID,
		&i.FinalizedAt,
	)
	return i, err
}

const getPricingModel = `-- name: GetPricingModel :one
SELECT version, valid_from, currency, document, imported_at
FROM pricing_models
WHERE version = $1
`

func (q *Queries) GetPricingModel(ctx context.Context, version string) (PricingModel, error) {
	row := q.db.QueryRow(ctx, getPricingModel, version)
	var i PricingModel
	err := row.Scan(
		&i.Version,
		&i.ValidFrom,
		&i.Currency,
		&i.Document,
		&i.ImportedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, period_from, period_to, kind, corrects_run_id, pricing_version,
       status, clouds, stats, started_at, completed_at
FROM runs
WHERE id = $1
`

// The same eleven columns without a FOR clause. An export only reads a run, so
// it takes no row lock: the FOR NO KEY UPDATE above would queue the export
// behind a run being finalized, and hold that finalization up in turn.
func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Kind,
		&i.CorrectsRunID,
		&i.PricingVersion,
		&i.Status,
		&i.Clouds,
		&i.Stats,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, period_from, period_to, kind, corrects_run_id, pricing_version,
       status, clouds, stats, started_at, completed_at
FROM runs
WHERE id = $1
FOR NO KEY UPDATE
`

// Reads a run under that same lock, which is how finalization sees a status
// that no concurrent writer can move underneath it.
func (q *Queries) GetRunForUpdate(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Kind,
		&i.CorrectsRunID,
		&i.PricingVersion,
		&i.Status,
		&i.Clouds,
		&i.Stats,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const hasCompleteRegularRun = `-- name: HasCompleteRegularRun :one
SELECT EXISTS (
    SELECT 1 FROM runs
    WHERE period_from = $1 AND kind = 'regular' AND status IN ('completed', 'finalized')
)
`

// Whether the period already has a regular run that got to the end. A
// finalized run counts as one: it is a completed run that closed its period.
func (q *Queries) HasCompleteRegularRun(ctx context.Context, periodFrom pgtype.Timestamptz) (bool, error) {
	row := q.db.QueryRow(ctx, hasCompleteRegularRun, periodFrom)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPricingModel = `-- name: InsertPricingModel :execrows
INSERT INTO pricing_models (version, valid_from, currency, document)
VALUES ($1, $2, $3, $4)
ON CONFLICT (version) DO NOTHING
`

type InsertPricingModelParams struct {
	Version   string
	ValidFrom pgtype.Timestamptz
	Currency  string
	Document  []byte
}

func (q *Queries) InsertPricingModel(ctx context.Context, arg InsertPricingModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPricingModel,
		arg.Version,
		arg.ValidFrom,
		arg.Currency,
		arg.Document,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProjectStatement = `-- name: InsertProjectStatement :exec
INSERT INTO project_statements (run_id, project_id, document, total, currency)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProjectStatementParams struct {
	RunID     pgtype.UUID
	ProjectID string
	Document  []byte
	Total     pgtype.Numeric
	Currency  string
}

func (q *Queries) InsertProjectStatement(ctx context.Context, arg InsertProjectStatementParams) error {
	_, err := q.db.Exec(ctx, insertProjectStatement,
		arg.RunID,
		arg.ProjectID,
		arg.Document,
		arg.Total,
		arg.Currency,
	)
	return err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (period_from, period_to, kind, corrects_run_id, pricing_version, clouds)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, started_at
`

type InsertRunParams struct {
	PeriodFrom     pgtype.Timestamptz
	PeriodTo       pgtype.Timestamptz
	Kind           string
	CorrectsRunID  pgtype.UUID
	PricingVersion pgtype.Text
	Clouds         []string
}

type InsertRunRow struct {
	ID        pgtype.UUID
	StartedAt pgtype.Timestamptz
}

// Opens a run. status stays at the column default 'running' and completed_at
// stays null until the run ends. The caller writes its records under the
// returned id and reports the returned start time. A regular run binds NULL for
// corrects_run_id, which is an invalid pgtype.UUID; a correction binds the run
// it corrects.
func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (InsertRunRow, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.Kind,
		arg.CorrectsRunID,
		arg.PricingVersion,
		arg.Clouds,
	)
	var i InsertRunRow
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}

const latestCompletedRegularRun = `-- name: LatestCompletedRegularRun :one
SELECT id FROM runs
WHERE period_from = $1 AND kind = 'regular' AND status = 'completed'
ORDER BY started_at DESC
LIMIT 1
`

// The run a period's current numbers come from. Superseding leaves at most one
// completed regular run per period, and the ordering settles which one a reader
// takes if it ever sees more.
func (q *Queries) LatestCompletedRegularRun(ctx context.Context, periodFrom pgtype.Timestamptz) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, latestCompletedRegularRun, periodFrom)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const latestFinalizedRun = `-- name: LatestFinalizedRun :one
SELECT id, kind, corrects_run_id, pricing_version, clouds, stats, started_at
FROM runs
WHERE period_from = $1 AND status = 'finalized'
ORDER BY started_at DESC
LIMIT 1
`

type LatestFinalizedRunRow struct {
	ID             pgtype.UUID
	Kind           string
	CorrectsRunID  pgtype.UUID
	PricingVersion pgtype.Text
	Clouds         []string
	Stats          []byte
	StartedAt      pgtype.Timestamptz
}

// The latest finalized truth of a period, which a correction diffs against and
// then names in corrects_run_id: the regular run that closed the period for
// the first correction, the last finalized correction after that (roadmap
// WP 3.9, item 5). detect-late reads the snapshot time out of its stats.
func (q *Queries) LatestFinalizedRun(ctx context.Context, periodFrom pgtype.Timestamptz) (LatestFinalizedRunRow, error) {
	row := q.db.QueryRow(ctx, latestFinalizedRun, periodFrom)
	var i LatestFinalizedRunRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CorrectsRunID,
		&i.PricingVersion,
		&i.Clouds,
		&i.Stats,
		&i.StartedAt,
	)
	return i, err
}

const listAdjustmentRecords = `-- name: ListAdjustmentRecords :many
SELECT id, run_id, project_id, relation_id, relation_type, relation_target,
       beneficiary, type, scope, rate, base, amount, currency
FROM adjustment_records
WHERE run_id = $1
ORDER BY project_id, relation_id, type, scope, rate, amount
`

// The adjustments a run applied, in a total order over the rows one run writes:
// a project's adjustments come from distinct relations, and one relation
// contributes at most one line per type and scope. A correction diffs these
// rows against its own, which is what the order is for.
func (q *Queries) ListAdjustmentRecords(ctx context.Context, runID pgtype.UUID) ([]AdjustmentRecord, error) {
	rows, err := q.db.Query(ctx, listAdjustmentRecords, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdjustmentRecord
	for rows.Next() {
		var i AdjustmentRecord
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ProjectID,
			&i.RelationID,
			&i.RelationType,
			&i.RelationTarget,
			&i.Beneficiary,
			&i.Type,
			&i.Scope,
			&i.Rate,
			&i.Base,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingPeriods = `-- name: ListBillingPeriods :many
SELECT period_from, status, finalized_run_id, finalized_at
FROM billing_periods
ORDER BY period_from
`

type ListBillingPeriodsRow struct {
	PeriodFrom     pgtype.Timestamptz
	Status         string
	FinalizedRunID pgtype.UUID
	FinalizedAt    pgtype.Timestamptz
}

func (q *Queries) ListBillingPeriods(ctx context.Context) ([]ListBillingPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listBillingPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillingPeriodsRow
	for rows.Next() {
		var i ListBillingPeriodsRow
		if err := rows.Scan(
			&i.PeriodFrom,
			&i.Status,
			&i.FinalizedRunID,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorrectionDeltas = `-- name: ListCorrectionDeltas :many
SELECT cloud, platform, resource_type, resource_id, project_id, dimension,
       old_amount, new_amount, delta, currency
FROM correction_deltas
WHERE run_id = $1
ORDER BY cloud, platform, resource_type, resource_id, project_id, dimension
`

type ListCorrectionDeltasRow struct {
	Cloud        string
	Platform     string
	ResourceType string
	ResourceID   string
	ProjectID    string
	Dimension    string
	OldAmount    pgtype.Numeric
	NewAmount    pgtype.Numeric
	Delta        pgtype.Numeric
	Currency     string
}

// The delta rows of a correction run, in the order corrections.Diff sorts by
// (internal/engine/corrections/corrections.go), so an export prints them as the
// correction computed them. idx_delta_run serves the filter.
func (q *Queries) ListCorrectionDeltas(ctx context.Context, runID pgtype.UUID) ([]ListCorrectionDeltasRow, error) {
	rows, err := q.db.Query(ctx, listCorrectionDeltas, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCorrectionDeltasRow
	for rows.Next() {
		var i ListCorrectionDeltasRow
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Dimension,
			&i.OldAmount,
			&i.NewAmount,
			&i.Delta,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingModels = `-- name: ListPricingModels :many
SELECT version, valid_from, currency, imported_at
FROM pricing_models
ORDER BY valid_from
`

type ListPricingModelsRow struct {
	Version    string
	ValidFrom  pgtype.Timestamptz
	Currency   string
	ImportedAt pgtype.Timestamptz
}

func (q *Queries) ListPricingModels(ctx context.Context) ([]ListPricingModelsRow, error) {
	rows, err := q.db.Query(ctx, listPricingModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingModelsRow
	for rows.Next() {
		var i ListPricingModelsRow
		if err := rows.Scan(
			&i.Version,
			&i.ValidFrom,
			&i.Currency,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStatements = `-- name: ListProjectStatements :many
SELECT id, run_id, project_id, document, total, currency
FROM project_statements
WHERE run_id = $1
ORDER BY project_id
`

func (q *Queries) ListProjectStatements(ctx context.Context, runID pgtype.UUID) ([]ProjectStatement, error) {
	rows, err := q.db.Query(ctx, listProjectStatements, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectStatement
	for rows.Next() {
		var i ProjectStatement
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ProjectID,
			&i.Document,
			&i.Total,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatedRecords = `-- name: ListRatedRecords :many
SELECT u.cloud, u.platform, u.resource_type, u.resource_id, u.project_id, u.state,
       u.from_ts, u.to_ts, u.usage, r.dimension, r.amount, r.currency
FROM rated_records r
JOIN usage_records u ON u.id = r.usage_record_id
WHERE r.run_id = $1
ORDER BY u.cloud, u.platform, u.resource_type, u.resource_id, u.from_ts, r.dimension
`

type ListRatedRecordsRow struct {
	Cloud        string
	Platform     string
	ResourceType string
	ResourceID   string
	ProjectID    string
	State        string
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
	Usage        []byte
	Dimension    string
	Amount       pgtype.Numeric
	Currency     string
}

// One row per rated record of a run, joined to the usage record it rates. The
// ordering is a total one: the drafts of one resource never overlap (draftsOf
// in internal/engine/metering/metering.go builds them from the intervals of a
// folded history), so from_ts is unique per resource within a run, and rating
// emits one record per usage record and dimension. That total order is what
// makes two exports of one run byte-identical. idx_rated_run serves the filter.
func (q *Queries) ListRatedRecords(ctx context.Context, runID pgtype.UUID) ([]ListRatedRecordsRow, error) {
	rows, err := q.db.Query(ctx, listRatedRecords, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatedRecordsRow
	for rows.Next() {
		var i ListRatedRecordsRow
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.State,
			&i.FromTs,
			&i.ToTs,
			&i.Usage,
			&i.Dimension,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRun = `-- name: LockRun :one
SELECT id FROM runs WHERE id = $1 FOR NO KEY UPDATE
`

// The first statement of a transaction that writes records. The trigger on the
// record tables locks the run FOR SHARE for every row it checks, and a
// transaction holding that lock which then updates the same run row has to
// escalate to FOR NO KEY UPDATE, which deadlocks two writers of one run.
// Taking the stronger lock up front is the ordering the comment on
// forbid_finalized_mutation in migration 0001 asks for.
func (q *Queries) LockRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockRun, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const pricingModelForPeriod = `-- name: PricingModelForPeriod :one
SELECT version, valid_from, currency, document, imported_at
FROM pricing_models
WHERE valid_from <= $1
ORDER BY valid_from DESC
LIMIT 1
`

func (q *Queries) PricingModelForPeriod(ctx context.Context, validFrom pgtype.Timestamptz) (PricingModel, error) {
	row := q.db.QueryRow(ctx, pricingModelForPeriod, validFrom)
	var i PricingModel
	err := row.Scan(
		&i.Version,
		&i.ValidFrom,
		&i.Currency,
		&i.Document,
		&i.ImportedAt,
	)
	return i, err
}

const reclaimStaleRuns = `-- name: ReclaimStaleRuns :many
UPDATE runs
SET status = 'failed',
    completed_at = now(),
    stats = stats || jsonb_build_object('error', 'the run''s process ended without completing it')
WHERE period_from = $1
  AND status = 'running'
  AND started_at < now() - interval '2 hours'
RETURNING id
`

// Reclaims the runs of a period that are still in flight with no process
// behind them. A killed process leaves its run at 'running' forever, and the
// period is blocked for as long as that row reads as a run in progress. The
// reason is merged into stats rather than written over it, so whatever the run
// had already counted survives.
//
// Age is what stands for the missing process, and the period lock cannot: that
// lock is session scoped on one pooled connection which stays protocol-idle for
// the whole run, so anything that closes only that connection -- an idle
// timeout, a reaper, a failover -- releases it while the process keeps metering.
// Two hours is longer than a run that is still alive: the CronJob's Job is
// killed after fifty minutes (activeDeadlineSeconds), and a month an operator
// meters by hand is minutes of work. Waiting costs nothing, because no query
// counts a 'running' row.
func (q *Queries) ReclaimStaleRuns(ctx context.Context, periodFrom pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, reclaimStaleRuns, periodFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBillingPeriodStatus = `-- name: SetBillingPeriodStatus :exec
UPDATE billing_periods
SET status = $2
WHERE period_from = $1
`

type SetBillingPeriodStatusParams struct {
	PeriodFrom pgtype.Timestamptz
	Status     string
}

func (q *Queries) SetBillingPeriodStatus(ctx context.Context, arg SetBillingPeriodStatusParams) error {
	_, err := q.db.Exec(ctx, setBillingPeriodStatus, arg.PeriodFrom, arg.Status)
	return err
}

const sumRatedByRun = `-- name: SumRatedByRun :many
SELECT u.cloud, u.platform, u.resource_type, u.resource_id, u.project_id, r.dimension,
       sum(r.amount)::numeric AS amount, r.currency
FROM rated_records r
JOIN usage_records u ON u.id = r.usage_record_id
WHERE r.run_id = $1
GROUP BY u.cloud, u.platform, u.resource_type, u.resource_id, u.project_id, r.dimension, r.currency
ORDER BY u.cloud, u.platform, u.resource_type, u.resource_id, u.project_id, r.dimension
`

type SumRatedByRunRow struct {
	Cloud        string
	Platform     string
	ResourceType string
	ResourceID   string
	ProjectID    string
	Dimension    string
	Amount       pgtype.Numeric
	Currency     string
}

// The amounts of one run summed per the key a correction diffs by (decision D6:
// cloud, platform, resource type, resource id, project id, dimension). The
// currency is grouped too, so a run rated in one currency yields one row per
// key. idx_rated_run serves the filter.
func (q *Queries) SumRatedByRun(ctx context.Context, runID pgtype.UUID) ([]SumRatedByRunRow, error) {
	rows, err := q.db.Query(ctx, sumRatedByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumRatedByRunRow
	for rows.Next() {
		var i SumRatedByRunRow
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Dimension,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeCompletedRuns = `-- name: SupersedeCompletedRuns :many
UPDATE runs
SET status = 'superseded'
WHERE period_from = $1 AND kind = $2 AND status = 'completed'
RETURNING id
`

type SupersedeCompletedRunsParams struct {
	PeriodFrom pgtype.Timestamptz
	Kind       string
}

// Retires the completed runs of the given kind that a new run of that kind
// replaces, so that a period carries at most one completed run per kind and a
// sum over that kind counts one set of records. It runs inside the new run's
// write transaction while that run is still 'running', so the filter on
// 'completed' never matches the run doing the superseding.
func (q *Queries) SupersedeCompletedRuns(ctx context.Context, arg SupersedeCompletedRunsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, supersedeCompletedRuns, arg.PeriodFrom, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryLockPeriod = `-- name: TryLockPeriod :one
SELECT pg_try_advisory_lock(hashtextextended('period:' || $1::text, 0))
`

// One process at a time meters a period. The lock is an advisory one rather
// than a row lock, because it is taken before the billing_periods row of the
// period exists. Its key is hashed from the period start as text, which the
// caller renders in UTC and RFC 3339, so that the same instant always reaches
// the same key: a timestamptz argument would be rendered by the server and the
// key would follow that session's DateStyle and TimeZone.
func (q *Queries) TryLockPeriod(ctx context.Context, periodFrom string) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockPeriod, periodFrom)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const unlockPeriod = `-- name: UnlockPeriod :one
SELECT pg_advisory_unlock(hashtextextended('period:' || $1::text, 0))
`

// Releases what TryLockPeriod took. An advisory lock is released by key, so the
// key expression has to stay identical to the one above.
func (q *Queries) UnlockPeriod(ctx context.Context, periodFrom string) (bool, error) {
	row := q.db.QueryRow(ctx, unlockPeriod, periodFrom)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const upsertBillingPeriod = `-- name: UpsertBillingPeriod :exec
INSERT INTO billing_periods (period_from, period_to)
VALUES ($1, $2)
ON CONFLICT (period_from) DO NOTHING
`

type UpsertBillingPeriodParams struct {
	PeriodFrom pgtype.Timestamptz
	PeriodTo   pgtype.Timestamptz
}

// Records that a period exists. The scheduler walks the months it is
// responsible for and calls this for each of them, so a period already known
// keeps the status and the finalization columns it has.
func (q *Queries) UpsertBillingPeriod(ctx context.Context, arg UpsertBillingPeriodParams) error {
	_, err := q.db.Exec(ctx, upsertBillingPeriod, arg.PeriodFrom, arg.PeriodTo)
	return err
}
