// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID          uuid.UUID
	TokenHash   string
	Role        string
	ProjectIds  []uuid.UUID
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID         int64
	At         pgtype.Timestamptz
	Actor      string
	Action     string
	ObjectType pgtype.Text
	ObjectID   pgtype.Text
	Details    []byte
}

type CurrentResource struct {
	Cloud         string
	Platform      string
	ResourceType  string
	ResourceID    string
	ProjectID     string
	State         string
	Size          []byte
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	LastEventType string
	LastEventAt   pgtype.Timestamptz
	LastPayload   []byte
}

type Event struct {
	EventID      string
	Timestamp    pgtype.Timestamptz
	ReceivedAt   pgtype.Timestamptz
	EventType    string
	Platform     string
	Cloud        string
	ResourceType string
	ResourceID   string
	ProjectID    string
	Source       string
	Payload      []byte
}

type IngestCredential struct {
	ID          uuid.UUID
	Platform    string
	Cloud       string
	TokenHash   string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Project struct {
	ID         uuid.UUID
	Platform   string
	Cloud      string
	ExternalID string
	Name       pgtype.Text
	Metadata   []byte
	CreatedAt  pgtype.Timestamptz
}

type ProjectRelation struct {
	ID           uuid.UUID
	SourceID     uuid.UUID
	TargetID     uuid.UUID
	RelationType string
	Metadata     []byte
	ValidFrom    pgtype.Timestamptz
	ValidTo      pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type RejectedEvent struct {
	ID         uuid.UUID
	ReceivedAt pgtype.Timestamptz
	Reason     string
	Raw        []byte
}

type ResourceType struct {
	Platform     string
	ResourceType string
	SizeSchema   []byte
	UpdatedAt    pgtype.Timestamptz
}

type SyncRun struct {
	ID          uuid.UUID
	Cloud       string
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	Status      string
	Stats       []byte
}
