// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeProjectRelation = `-- name: CloseProjectRelation :execrows
UPDATE project_relations
SET valid_to = now()
WHERE id = $1 AND source_id = $2 AND valid_to IS NULL
`

type CloseProjectRelationParams struct {
	ID       uuid.UUID
	SourceID uuid.UUID
}

// A relation is closed rather than deleted, so that a read at an earlier
// instant still finds it. The row count tells the close apart from the relation
// that was closed already, which no longer matches.
func (q *Queries) CloseProjectRelation(ctx context.Context, arg CloseProjectRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeProjectRelation, arg.ID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeSyncRun = `-- name: CompleteSyncRun :exec
UPDATE sync_runs
SET status = $2, stats = $3, completed_at = now()
WHERE id = $1
`

type CompleteSyncRunParams struct {
	ID     uuid.UUID
	Status string
	Stats  []byte
}

func (q *Queries) CompleteSyncRun(ctx context.Context, arg CompleteSyncRunParams) error {
	_, err := q.db.Exec(ctx, completeSyncRun, arg.ID, arg.Status, arg.Stats)
	return err
}

const countEventsForResource = `-- name: CountEventsForResource :one
SELECT count(*)
FROM (
    SELECT 1
    FROM events
    WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
      AND ($4::text[] IS NULL
           OR (cloud, project_id) IN (SELECT unnest($4::text[]),
                                             unnest($5::text[])))
    LIMIT $6
) probe
`

type CountEventsForResourceParams struct {
	Cloud         string
	ResourceType  string
	ResourceID    string
	ScopeClouds   []string
	ScopeProjects []string
	ProbeLimit    int32
}

// How long the history above is under the same scope, counted no further than
// probe_limit. The unpaginated per-resource routes ask this before they read
// anything, because the bound they enforce is a memory bound and the read above
// materializes every row it returns before the caller sees the first one:
// deciding the refusal off the rows themselves would cost exactly the payloads
// the refusal exists to avoid.
//
// The answer saturates at probe_limit, and a caller reads it as "at least this
// many" rather than as the length of the history. A plain count(*) cannot stop
// early: it would answer the bounded question of whether the history is too long
// by walking every event the resource has, on exactly the request the bound
// exists to keep cheap, and this table has no ceiling on how many that is. The
// inner LIMIT is what stops the walk at the only rows the decision needs.
func (q *Queries) CountEventsForResource(ctx context.Context, arg CountEventsForResourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsForResource,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.ProbeLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (token_hash, role, project_ids, description)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAPITokenParams struct {
	TokenHash   string
	Role        string
	ProjectIds  []uuid.UUID
	Description pgtype.Text
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.TokenHash,
		arg.Role,
		arg.ProjectIds,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createIngestCredential = `-- name: CreateIngestCredential :one
INSERT INTO ingest_credentials (platform, cloud, token_hash, description)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateIngestCredentialParams struct {
	Platform    string
	Cloud       string
	TokenHash   string
	Description pgtype.Text
}

func (q *Queries) CreateIngestCredential(ctx context.Context, arg CreateIngestCredentialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createIngestCredential,
		arg.Platform,
		arg.Cloud,
		arg.TokenHash,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAPITokenByTokenHash = `-- name: GetAPITokenByTokenHash :one
SELECT id, token_hash, role, project_ids, description, created_at, revoked_at
FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPITokenByTokenHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByTokenHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.ProjectIds,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenForUpdate = `-- name: GetAPITokenForUpdate :one
SELECT id, token_hash, role, project_ids, description, created_at, revoked_at
FROM api_tokens
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAPITokenForUpdate(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenForUpdate, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.ProjectIds,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCurrentResource = `-- name: GetCurrentResource :one
SELECT cloud, platform, resource_type, resource_id, project_id, state, size,
       created_at, deleted_at, last_event_type, last_event_at, last_payload
FROM current_resources
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
`

type GetCurrentResourceParams struct {
	Cloud        string
	ResourceType string
	ResourceID   string
}

// The read path of one projection row. It is GetCurrentResourceForUpdate
// without the row lock: a read must not make a writer wait on it.
func (q *Queries) GetCurrentResource(ctx context.Context, arg GetCurrentResourceParams) (CurrentResource, error) {
	row := q.db.QueryRow(ctx, getCurrentResource, arg.Cloud, arg.ResourceType, arg.ResourceID)
	var i CurrentResource
	err := row.Scan(
		&i.Cloud,
		&i.Platform,
		&i.ResourceType,
		&i.ResourceID,
		&i.ProjectID,
		&i.State,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.LastEventType,
		&i.LastEventAt,
		&i.LastPayload,
	)
	return i, err
}

const getCurrentResourceForUpdate = `-- name: GetCurrentResourceForUpdate :one
SELECT cloud, platform, resource_type, resource_id, project_id, state, size,
       created_at, deleted_at, last_event_type, last_event_at, last_payload
FROM current_resources
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
FOR UPDATE
`

type GetCurrentResourceForUpdateParams struct {
	Cloud        string
	ResourceType string
	ResourceID   string
}

func (q *Queries) GetCurrentResourceForUpdate(ctx context.Context, arg GetCurrentResourceForUpdateParams) (CurrentResource, error) {
	row := q.db.QueryRow(ctx, getCurrentResourceForUpdate, arg.Cloud, arg.ResourceType, arg.ResourceID)
	var i CurrentResource
	err := row.Scan(
		&i.Cloud,
		&i.Platform,
		&i.ResourceType,
		&i.ResourceID,
		&i.ProjectID,
		&i.State,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.LastEventType,
		&i.LastEventAt,
		&i.LastPayload,
	)
	return i, err
}

const getIngestCredentialByTokenHash = `-- name: GetIngestCredentialByTokenHash :one
SELECT id, platform, cloud, token_hash, description, created_at, revoked_at
FROM ingest_credentials
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetIngestCredentialByTokenHash(ctx context.Context, tokenHash string) (IngestCredential, error) {
	row := q.db.QueryRow(ctx, getIngestCredentialByTokenHash, tokenHash)
	var i IngestCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Cloud,
		&i.TokenHash,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getIngestCredentialForUpdate = `-- name: GetIngestCredentialForUpdate :one
SELECT id, platform, cloud, token_hash, description, created_at, revoked_at
FROM ingest_credentials
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetIngestCredentialForUpdate(ctx context.Context, id uuid.UUID) (IngestCredential, error) {
	row := q.db.QueryRow(ctx, getIngestCredentialForUpdate, id)
	var i IngestCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Cloud,
		&i.TokenHash,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getLastCompletedSyncStartedAt = `-- name: GetLastCompletedSyncStartedAt :one
SELECT started_at
FROM sync_runs
WHERE cloud = $1 AND status = 'completed'
ORDER BY started_at DESC
LIMIT 1
`

// Where an incremental sync starts. The bound is the previous run's started_at
// rather than its completed_at, so that the window overlaps that run and a
// change made while it was working cannot fall between the two.
func (q *Queries) GetLastCompletedSyncStartedAt(ctx context.Context, cloud string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastCompletedSyncStartedAt, cloud)
	var started_at pgtype.Timestamptz
	err := row.Scan(&started_at)
	return started_at, err
}

const getProject = `-- name: GetProject :one
SELECT id, platform, cloud, external_id, name, metadata, created_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Cloud,
		&i.ExternalID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectRefsByIDs = `-- name: GetProjectRefsByIDs :many
SELECT id, cloud, external_id
FROM projects
WHERE id = ANY($1::uuid[])
`

type GetProjectRefsByIDsRow struct {
	ID         uuid.UUID
	Cloud      string
	ExternalID string
}

func (q *Queries) GetProjectRefsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetProjectRefsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProjectRefsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectRefsByIDsRow
	for rows.Next() {
		var i GetProjectRefsByIDsRow
		if err := rows.Scan(&i.ID, &i.Cloud, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectRelation = `-- name: GetProjectRelation :one
SELECT id, source_id, target_id, relation_type, metadata, valid_from, valid_to,
       created_at
FROM project_relations
WHERE id = $1 AND source_id = $2
`

type GetProjectRelationParams struct {
	ID       uuid.UUID
	SourceID uuid.UUID
}

// The source project is part of every single-relation key: a relation is
// addressed under the project it leaves, and an id that belongs to another
// project reads as absent rather than as someone else's row.
func (q *Queries) GetProjectRelation(ctx context.Context, arg GetProjectRelationParams) (ProjectRelation, error) {
	row := q.db.QueryRow(ctx, getProjectRelation, arg.ID, arg.SourceID)
	var i ProjectRelation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.Metadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectsByIDs = `-- name: GetProjectsByIDs :many
SELECT id, platform, cloud, external_id, name, metadata, created_at
FROM projects
WHERE id = ANY($1::uuid[])
`

// The batch form of the read above, for the callers that resolve a whole set of
// ids at once. GetProjectRefsByIDs is the same read narrowed to the two columns
// an event needs.
func (q *Queries) GetProjectsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Cloud,
			&i.ExternalID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceType = `-- name: GetResourceType :one
SELECT platform, resource_type, size_schema, updated_at
FROM resource_types
WHERE platform = $1 AND resource_type = $2
`

type GetResourceTypeParams struct {
	Platform     string
	ResourceType string
}

func (q *Queries) GetResourceType(ctx context.Context, arg GetResourceTypeParams) (ResourceType, error) {
	row := q.db.QueryRow(ctx, getResourceType, arg.Platform, arg.ResourceType)
	var i ResourceType
	err := row.Scan(
		&i.Platform,
		&i.ResourceType,
		&i.SizeSchema,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncRun = `-- name: GetSyncRun :one
SELECT id, cloud, started_at, completed_at, status, stats
FROM sync_runs
WHERE id = $1
`

// Reads a finished run back, for the tests that compare the stored row against
// the response the sync returned.
func (q *Queries) GetSyncRun(ctx context.Context, id uuid.UUID) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getSyncRun, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.Cloud,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.Stats,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor, action, object_type, object_id, details)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	Actor      string
	Action     string
	ObjectType pgtype.Text
	ObjectID   pgtype.Text
	Details    []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Actor,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Details,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (event_id, timestamp, event_type, platform, cloud,
                    resource_type, resource_id, project_id, source, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (event_id, timestamp) DO NOTHING
RETURNING received_at
`

type InsertEventParams struct {
	EventID      string
	Timestamp    pgtype.Timestamptz
	EventType    string
	Platform     string
	Cloud        string
	ResourceType string
	ResourceID   string
	ProjectID    string
	Source       string
	Payload      []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventID,
		arg.Timestamp,
		arg.EventType,
		arg.Platform,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.ProjectID,
		arg.Source,
		arg.Payload,
	)
	var received_at pgtype.Timestamptz
	err := row.Scan(&received_at)
	return received_at, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (platform, cloud, external_id, name, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, platform, cloud, external_id, name, metadata, created_at
`

type InsertProjectParams struct {
	Platform   string
	Cloud      string
	ExternalID string
	Name       pgtype.Text
	Metadata   []byte
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.Platform,
		arg.Cloud,
		arg.ExternalID,
		arg.Name,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Cloud,
		&i.ExternalID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertProjectRelation = `-- name: InsertProjectRelation :one
INSERT INTO project_relations (source_id, target_id, relation_type, metadata,
                               valid_from)
VALUES ($1, $2, $3, $4, COALESCE($5::timestamptz, now()))
RETURNING id, source_id, target_id, relation_type, metadata, valid_from,
          valid_to, created_at
`

type InsertProjectRelationParams struct {
	SourceID     uuid.UUID
	TargetID     uuid.UUID
	RelationType string
	Metadata     []byte
	ValidFrom    pgtype.Timestamptz
}

// A NULL valid_from means the relation starts when it is written, which is what
// a request that names no start asks for.
func (q *Queries) InsertProjectRelation(ctx context.Context, arg InsertProjectRelationParams) (ProjectRelation, error) {
	row := q.db.QueryRow(ctx, insertProjectRelation,
		arg.SourceID,
		arg.TargetID,
		arg.RelationType,
		arg.Metadata,
		arg.ValidFrom,
	)
	var i ProjectRelation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.Metadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const insertRejectedEvent = `-- name: InsertRejectedEvent :exec
INSERT INTO rejected_events (reason, raw)
VALUES ($1, $2)
`

type InsertRejectedEventParams struct {
	Reason string
	Raw    []byte
}

func (q *Queries) InsertRejectedEvent(ctx context.Context, arg InsertRejectedEventParams) error {
	_, err := q.db.Exec(ctx, insertRejectedEvent, arg.Reason, arg.Raw)
	return err
}

const insertSyncRun = `-- name: InsertSyncRun :one
INSERT INTO sync_runs (cloud)
VALUES ($1)
RETURNING id
`

// The run row is written before the adapter is called, so that a run in flight
// can be seen while it works: status defaults to 'running' in the schema, and
// the row is left at that value until the run finishes.
func (q *Queries) InsertSyncRun(ctx context.Context, cloud string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSyncRun, cloud)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listActiveAttributingRelations = `-- name: ListActiveAttributingRelations :many
SELECT id, source_id, target_id, relation_type, metadata, valid_from, valid_to,
       created_at
FROM project_relations
WHERE source_id = ANY($1::uuid[])
  AND valid_to IS NULL
  AND relation_type = ANY($2::text[])
ORDER BY source_id, created_at, id
`

type ListActiveAttributingRelationsParams struct {
	SourceIds     []uuid.UUID
	RelationTypes []string
}

// The walk the cycle check runs, which asks about the graph as it is rather
// than as it stood at some instant: only the open relations of the attributing
// types can carry cost, so only they can close a cycle that matters.
func (q *Queries) ListActiveAttributingRelations(ctx context.Context, arg ListActiveAttributingRelationsParams) ([]ProjectRelation, error) {
	rows, err := q.db.Query(ctx, listActiveAttributingRelations, arg.SourceIds, arg.RelationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRelation
	for rows.Next() {
		var i ProjectRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Metadata,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentResources = `-- name: ListCurrentResources :many
SELECT cloud, platform, resource_type, resource_id, project_id, state, size,
       created_at, deleted_at, last_event_type, last_event_at, last_payload
FROM current_resources
WHERE ($1::text IS NULL OR cloud = $1)
  AND ($2::text IS NULL OR platform = $2)
  AND ($3::text IS NULL OR project_id = $3)
  AND ($4::text IS NULL OR resource_type = $4)
  AND ($5::text IS NULL OR state = $5)
  -- The status filter of the API, as the one boolean the two halves of the
  -- fleet differ in: true serves the deleted rows, false the ones that live,
  -- and NULL both.
  AND ($6::boolean IS NULL OR (state = 'deleted') = $6)
  AND ($7::text[] IS NULL
       OR (cloud, project_id) IN (SELECT unnest($7::text[]),
                                         unnest($8::text[])))
  -- Every bound is cast: inside a row comparison sqlc reads the type of the
  -- later placeholders off the first one, which is why the events cursor above
  -- casts both of its bounds too.
  AND ($9::text IS NULL
       OR (cloud, resource_type, resource_id) > ($9::text,
                                                 $10::text,
                                                 $11::text))
ORDER BY cloud, resource_type, resource_id
LIMIT $12
`

type ListCurrentResourcesParams struct {
	Cloud              pgtype.Text
	Platform           pgtype.Text
	ProjectID          pgtype.Text
	ResourceType       pgtype.Text
	State              pgtype.Text
	Deleted            pgtype.Bool
	ScopeClouds        []string
	ScopeProjects      []string
	CursorCloud        pgtype.Text
	CursorResourceType pgtype.Text
	CursorResourceID   pgtype.Text
	PageSize           int32
}

func (q *Queries) ListCurrentResources(ctx context.Context, arg ListCurrentResourcesParams) ([]CurrentResource, error) {
	rows, err := q.db.Query(ctx, listCurrentResources,
		arg.Cloud,
		arg.Platform,
		arg.ProjectID,
		arg.ResourceType,
		arg.State,
		arg.Deleted,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.CursorCloud,
		arg.CursorResourceType,
		arg.CursorResourceID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentResource
	for rows.Next() {
		var i CurrentResource
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.State,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.LastEventType,
			&i.LastEventAt,
			&i.LastPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentResourcesByCloud = `-- name: ListCurrentResourcesByCloud :many
SELECT resource_type, resource_id, project_id, state, size, last_event_at
FROM current_resources
WHERE cloud = $1
`

type ListCurrentResourcesByCloudRow struct {
	ResourceType string
	ResourceID   string
	ProjectID    string
	State        string
	Size         []byte
	LastEventAt  pgtype.Timestamptz
}

// The stored side of the reconciliation diff, in the six columns the diff
// reads. Deleted resources are part of the answer: one the adapter reports
// again has come back, and telling that apart from a first sighting needs the
// row. last_event_at is what a correction has to be dated past to reach the
// row at all: one the fold orders before it replays the history instead.
func (q *Queries) ListCurrentResourcesByCloud(ctx context.Context, cloud string) ([]ListCurrentResourcesByCloudRow, error) {
	rows, err := q.db.Query(ctx, listCurrentResourcesByCloud, cloud)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentResourcesByCloudRow
	for rows.Next() {
		var i ListCurrentResourcesByCloudRow
		if err := rows.Scan(
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.State,
			&i.Size,
			&i.LastEventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT event_id, timestamp, received_at, event_type, platform, cloud,
       resource_type, resource_id, project_id, source, payload
FROM events
WHERE ($1::text IS NULL OR cloud = $1)
  AND ($2::text IS NULL OR platform = $2)
  AND ($3::text IS NULL OR project_id = $3)
  AND ($4::text IS NULL OR resource_type = $4)
  AND ($5::text IS NULL OR event_type = $5)
  AND ($6::text IS NULL OR source = $6)
  AND ($7::timestamptz IS NULL OR timestamp >= $7)
  AND ($8::timestamptz IS NULL OR timestamp < $8)
  AND ($9::text[] IS NULL
       OR (cloud, project_id) IN (SELECT unnest($9::text[]),
                                         unnest($10::text[])))
  -- Both bounds are cast: inside a row comparison sqlc reads the type of the
  -- second placeholder off the first one, which would make the event id a
  -- timestamp in the generated parameters.
  AND ($11::timestamptz IS NULL
       OR (timestamp, event_id) > ($11::timestamptz,
                                   $12::text))
ORDER BY timestamp, event_id
LIMIT $13
`

type ListEventsParams struct {
	Cloud         pgtype.Text
	Platform      pgtype.Text
	ProjectID     pgtype.Text
	ResourceType  pgtype.Text
	EventType     pgtype.Text
	Source        pgtype.Text
	FromTs        pgtype.Timestamptz
	ToTs          pgtype.Timestamptz
	ScopeClouds   []string
	ScopeProjects []string
	CursorTs      pgtype.Timestamptz
	CursorEventID pgtype.Text
	PageSize      int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.Cloud,
		arg.Platform,
		arg.ProjectID,
		arg.ResourceType,
		arg.EventType,
		arg.Source,
		arg.FromTs,
		arg.ToTs,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.CursorTs,
		arg.CursorEventID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.Timestamp,
			&i.ReceivedAt,
			&i.EventType,
			&i.Platform,
			&i.Cloud,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Source,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForResource = `-- name: ListEventsForResource :many
SELECT event_id, timestamp, received_at, event_type, platform, cloud,
       resource_type, resource_id, project_id, source, payload
FROM events
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
  -- The same pair filter the event list runs, per event rather than per
  -- resource: a transfer moves the resource to its new project, and the events
  -- it carried before the transfer stay the old project's alone.
  AND ($4::text[] IS NULL
       OR (cloud, project_id) IN (SELECT unnest($4::text[]),
                                         unnest($5::text[])))
ORDER BY timestamp, received_at, event_id
LIMIT $6
`

type ListEventsForResourceParams struct {
	Cloud         string
	ResourceType  string
	ResourceID    string
	ScopeClouds   []string
	ScopeProjects []string
	PageSize      pgtype.Int4
}

// The history of one resource. Two callers read it: the projection replay, which
// folds every event there is under no scope and no bound, and the two
// per-resource routes of the API, which pass both. A NULL page size is every
// row, which is what the replay folds.
func (q *Queries) ListEventsForResource(ctx context.Context, arg ListEventsForResourceParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForResource,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.Timestamp,
			&i.ReceivedAt,
			&i.EventType,
			&i.Platform,
			&i.Cloud,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Source,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectRelations = `-- name: ListProjectRelations :many
SELECT id, source_id, target_id, relation_type, metadata, valid_from, valid_to,
       created_at
FROM project_relations
WHERE (($1::boolean AND source_id = $2)
       OR ($3::boolean AND target_id = $2))
  AND valid_from <= $4
  AND (valid_to IS NULL OR valid_to > $4)
  AND ($5::text IS NULL
       OR relation_type = $5)
ORDER BY created_at, id
`

type ListProjectRelationsParams struct {
	Outgoing     bool
	ProjectID    uuid.UUID
	Incoming     bool
	At           pgtype.Timestamptz
	RelationType pgtype.Text
}

// The relations of one project as they stood at one instant. The two direction
// flags are what the direction filter of the API comes down to: a relation
// counts when it leaves the project and outgoing is set, or reaches it and
// incoming is.
func (q *Queries) ListProjectRelations(ctx context.Context, arg ListProjectRelationsParams) ([]ProjectRelation, error) {
	rows, err := q.db.Query(ctx, listProjectRelations,
		arg.Outgoing,
		arg.ProjectID,
		arg.Incoming,
		arg.At,
		arg.RelationType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRelation
	for rows.Next() {
		var i ProjectRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Metadata,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, platform, cloud, external_id, name, metadata, created_at
FROM projects
WHERE ($1::text IS NULL OR platform = $1)
  AND ($2::text IS NULL OR cloud = $2)
  AND ($3::text IS NULL
       OR external_id = $3)
  -- Both bounds are cast, for the reason the events cursor above names.
  AND ($4::text IS NULL
       OR (cloud, external_id) > ($4::text,
                                  $5::text))
ORDER BY cloud, external_id
LIMIT $6
`

type ListProjectsParams struct {
	Platform         pgtype.Text
	Cloud            pgtype.Text
	ExternalID       pgtype.Text
	CursorCloud      pgtype.Text
	CursorExternalID pgtype.Text
	PageSize         int32
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.Platform,
		arg.Cloud,
		arg.ExternalID,
		arg.CursorCloud,
		arg.CursorExternalID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Cloud,
			&i.ExternalID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRejectedEvents = `-- name: ListRejectedEvents :many
SELECT id, received_at, reason, raw
FROM rejected_events
WHERE ($1::timestamptz IS NULL OR received_at >= $1)
  AND ($2::timestamptz IS NULL OR received_at < $2)
  -- Both bounds are cast, for the reason the events cursor above names.
  AND ($3::timestamptz IS NULL
       OR (received_at, id) > ($3::timestamptz, $4::uuid))
ORDER BY received_at, id
LIMIT $5
`

type ListRejectedEventsParams struct {
	FromTs   pgtype.Timestamptz
	ToTs     pgtype.Timestamptz
	CursorTs pgtype.Timestamptz
	CursorID pgtype.UUID
	PageSize int32
}

func (q *Queries) ListRejectedEvents(ctx context.Context, arg ListRejectedEventsParams) ([]RejectedEvent, error) {
	rows, err := q.db.Query(ctx, listRejectedEvents,
		arg.FromTs,
		arg.ToTs,
		arg.CursorTs,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RejectedEvent
	for rows.Next() {
		var i RejectedEvent
		if err := rows.Scan(
			&i.ID,
			&i.ReceivedAt,
			&i.Reason,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsValidAt = `-- name: ListRelationsValidAt :many
SELECT id, source_id, target_id, relation_type, metadata, valid_from, valid_to,
       created_at
FROM project_relations
WHERE source_id = ANY($1::uuid[])
  AND valid_from <= $2
  AND (valid_to IS NULL OR valid_to > $2)
  AND ($3::text IS NULL
       OR relation_type = $3)
ORDER BY source_id, created_at, id
`

type ListRelationsValidAtParams struct {
	SourceIds    []uuid.UUID
	At           pgtype.Timestamptz
	RelationType pgtype.Text
}

// The relations of a whole set of projects at one instant, for the callers that
// walk the graph rather than serve one project's list.
func (q *Queries) ListRelationsValidAt(ctx context.Context, arg ListRelationsValidAtParams) ([]ProjectRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsValidAt, arg.SourceIds, arg.At, arg.RelationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRelation
	for rows.Next() {
		var i ProjectRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Metadata,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceKeys = `-- name: ListResourceKeys :many
SELECT DISTINCT cloud, resource_type, resource_id
FROM events
WHERE ($1::text IS NULL OR cloud = $1)
  AND ($2::text IS NULL OR resource_type = $2)
ORDER BY cloud, resource_type, resource_id
`

type ListResourceKeysParams struct {
	Cloud        pgtype.Text
	ResourceType pgtype.Text
}

type ListResourceKeysRow struct {
	Cloud        string
	ResourceType string
	ResourceID   string
}

func (q *Queries) ListResourceKeys(ctx context.Context, arg ListResourceKeysParams) ([]ListResourceKeysRow, error) {
	rows, err := q.db.Query(ctx, listResourceKeys, arg.Cloud, arg.ResourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceKeysRow
	for rows.Next() {
		var i ListResourceKeysRow
		if err := rows.Scan(&i.Cloud, &i.ResourceType, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceTypes = `-- name: ListResourceTypes :many
SELECT platform, resource_type, size_schema, updated_at
FROM resource_types
ORDER BY platform, resource_type
`

func (q *Queries) ListResourceTypes(ctx context.Context) ([]ResourceType, error) {
	rows, err := q.db.Query(ctx, listResourceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceType
	for rows.Next() {
		var i ResourceType
		if err := rows.Scan(
			&i.Platform,
			&i.ResourceType,
			&i.SizeSchema,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttributingRelations = `-- name: LockAttributingRelations :exec
SELECT pg_advisory_xact_lock(hashtextextended('project_relations:attributing', 0))
`

// Serializes the creation of attributing relations, so that two racing inserts
// cannot each pass the cycle walk and leave a cycle behind.
func (q *Queries) LockAttributingRelations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAttributingRelations)
	return err
}

const lockResource = `-- name: LockResource :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':' || $2::text || ':' || $3::text, 0))
`

type LockResourceParams struct {
	Column1 string
	Column2 string
	Column3 string
}

func (q *Queries) LockResource(ctx context.Context, arg LockResourceParams) error {
	_, err := q.db.Exec(ctx, lockResource, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const revokeIngestCredential = `-- name: RevokeIngestCredential :exec
UPDATE ingest_credentials
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeIngestCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeIngestCredential, id)
	return err
}

const trySyncLock = `-- name: TrySyncLock :one
SELECT pg_try_advisory_lock(hashtextextended('sync:' || $1::text, 0))
`

// Keeps two syncs of one cloud from running at once. The lock is held for the
// session rather than for the transaction, as LockResource is, because a run
// spans several transactions.
func (q *Queries) TrySyncLock(ctx context.Context, dollar_1 string) (bool, error) {
	row := q.db.QueryRow(ctx, trySyncLock, dollar_1)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const unlockSync = `-- name: UnlockSync :exec
SELECT pg_advisory_unlock(hashtextextended('sync:' || $1::text, 0))
`

func (q *Queries) UnlockSync(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, unlockSync, dollar_1)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($2, name),
    metadata = COALESCE($3, metadata)
WHERE id = $1
RETURNING id, platform, cloud, external_id, name, metadata, created_at
`

type UpdateProjectParams struct {
	ID       uuid.UUID
	Name     pgtype.Text
	Metadata []byte
}

// A NULL parameter leaves the column as it stands, so a request that carries
// one field updates that field alone.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Metadata)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Cloud,
		&i.ExternalID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectRelation = `-- name: UpdateProjectRelation :one
UPDATE project_relations
SET metadata = COALESCE($3, metadata),
    valid_to = COALESCE($4, valid_to)
WHERE id = $1 AND source_id = $2
RETURNING id, source_id, target_id, relation_type, metadata, valid_from,
          valid_to, created_at
`

type UpdateProjectRelationParams struct {
	ID       uuid.UUID
	SourceID uuid.UUID
	Metadata []byte
	ValidTo  pgtype.Timestamptz
}

func (q *Queries) UpdateProjectRelation(ctx context.Context, arg UpdateProjectRelationParams) (ProjectRelation, error) {
	row := q.db.QueryRow(ctx, updateProjectRelation,
		arg.ID,
		arg.SourceID,
		arg.Metadata,
		arg.ValidTo,
	)
	var i ProjectRelation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.Metadata,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCurrentResource = `-- name: UpsertCurrentResource :exec
INSERT INTO current_resources (cloud, platform, resource_type, resource_id,
                               project_id, state, size, created_at, deleted_at,
                               last_event_type, last_event_at, last_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (cloud, resource_type, resource_id) DO UPDATE
SET platform = EXCLUDED.platform,
    project_id = EXCLUDED.project_id,
    state = EXCLUDED.state,
    size = EXCLUDED.size,
    created_at = EXCLUDED.created_at,
    deleted_at = EXCLUDED.deleted_at,
    last_event_type = EXCLUDED.last_event_type,
    last_event_at = EXCLUDED.last_event_at,
    last_payload = EXCLUDED.last_payload
`

type UpsertCurrentResourceParams struct {
	Cloud         string
	Platform      string
	ResourceType  string
	ResourceID    string
	ProjectID     string
	State         string
	Size          []byte
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	LastEventType string
	LastEventAt   pgtype.Timestamptz
	LastPayload   []byte
}

func (q *Queries) UpsertCurrentResource(ctx context.Context, arg UpsertCurrentResourceParams) error {
	_, err := q.db.Exec(ctx, upsertCurrentResource,
		arg.Cloud,
		arg.Platform,
		arg.ResourceType,
		arg.ResourceID,
		arg.ProjectID,
		arg.State,
		arg.Size,
		arg.CreatedAt,
		arg.DeletedAt,
		arg.LastEventType,
		arg.LastEventAt,
		arg.LastPayload,
	)
	return err
}

const upsertResourceType = `-- name: UpsertResourceType :one
INSERT INTO resource_types (platform, resource_type, size_schema)
VALUES ($1, $2, $3)
ON CONFLICT (platform, resource_type) DO UPDATE
SET size_schema = EXCLUDED.size_schema,
    updated_at = now()
RETURNING platform, resource_type, size_schema, updated_at
`

type UpsertResourceTypeParams struct {
	Platform     string
	ResourceType string
	SizeSchema   []byte
}

func (q *Queries) UpsertResourceType(ctx context.Context, arg UpsertResourceTypeParams) (ResourceType, error) {
	row := q.db.QueryRow(ctx, upsertResourceType, arg.Platform, arg.ResourceType, arg.SizeSchema)
	var i ResourceType
	err := row.Scan(
		&i.Platform,
		&i.ResourceType,
		&i.SizeSchema,
		&i.UpdatedAt,
	)
	return i, err
}
