// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsForResource = `-- name: CountEventsForResource :one
SELECT count(*)
FROM (
    SELECT 1
    FROM events
    WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
      AND ($4::text[] IS NULL
           OR (cloud, project_id) IN (SELECT unnest($4::text[]),
                                             unnest($5::text[])))
    LIMIT $6
) probe
`

type CountEventsForResourceParams struct {
	Cloud         string
	ResourceType  string
	ResourceID    string
	ScopeClouds   []string
	ScopeProjects []string
	ProbeLimit    int32
}

// How long the history above is under the same scope, counted no further than
// probe_limit. The unpaginated per-resource routes ask this before they read
// anything, because the bound they enforce is a memory bound and the read above
// materializes every row it returns before the caller sees the first one:
// deciding the refusal off the rows themselves would cost exactly the payloads
// the refusal exists to avoid.
//
// The answer saturates at probe_limit, and a caller reads it as "at least this
// many" rather than as the length of the history. A plain count(*) cannot stop
// early: it would answer the bounded question of whether the history is too long
// by walking every event the resource has, on exactly the request the bound
// exists to keep cheap, and this table has no ceiling on how many that is. The
// inner LIMIT is what stops the walk at the only rows the decision needs.
func (q *Queries) CountEventsForResource(ctx context.Context, arg CountEventsForResourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsForResource,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.ProbeLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (token_hash, role, project_ids, description)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAPITokenParams struct {
	TokenHash   string
	Role        string
	ProjectIds  []uuid.UUID
	Description pgtype.Text
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.TokenHash,
		arg.Role,
		arg.ProjectIds,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createIngestCredential = `-- name: CreateIngestCredential :one
INSERT INTO ingest_credentials (platform, cloud, token_hash, description)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateIngestCredentialParams struct {
	Platform    string
	Cloud       string
	TokenHash   string
	Description pgtype.Text
}

func (q *Queries) CreateIngestCredential(ctx context.Context, arg CreateIngestCredentialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createIngestCredential,
		arg.Platform,
		arg.Cloud,
		arg.TokenHash,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAPITokenByTokenHash = `-- name: GetAPITokenByTokenHash :one
SELECT id, token_hash, role, project_ids, description, created_at, revoked_at
FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPITokenByTokenHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByTokenHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.ProjectIds,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenForUpdate = `-- name: GetAPITokenForUpdate :one
SELECT id, token_hash, role, project_ids, description, created_at, revoked_at
FROM api_tokens
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAPITokenForUpdate(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenForUpdate, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.ProjectIds,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCurrentResource = `-- name: GetCurrentResource :one
SELECT cloud, platform, resource_type, resource_id, project_id, state, size,
       created_at, deleted_at, last_event_type, last_event_at, last_payload
FROM current_resources
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
`

type GetCurrentResourceParams struct {
	Cloud        string
	ResourceType string
	ResourceID   string
}

// The read path of one projection row. It is GetCurrentResourceForUpdate
// without the row lock: a read must not make a writer wait on it.
func (q *Queries) GetCurrentResource(ctx context.Context, arg GetCurrentResourceParams) (CurrentResource, error) {
	row := q.db.QueryRow(ctx, getCurrentResource, arg.Cloud, arg.ResourceType, arg.ResourceID)
	var i CurrentResource
	err := row.Scan(
		&i.Cloud,
		&i.Platform,
		&i.ResourceType,
		&i.ResourceID,
		&i.ProjectID,
		&i.State,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.LastEventType,
		&i.LastEventAt,
		&i.LastPayload,
	)
	return i, err
}

const getCurrentResourceForUpdate = `-- name: GetCurrentResourceForUpdate :one
SELECT cloud, platform, resource_type, resource_id, project_id, state, size,
       created_at, deleted_at, last_event_type, last_event_at, last_payload
FROM current_resources
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
FOR UPDATE
`

type GetCurrentResourceForUpdateParams struct {
	Cloud        string
	ResourceType string
	ResourceID   string
}

func (q *Queries) GetCurrentResourceForUpdate(ctx context.Context, arg GetCurrentResourceForUpdateParams) (CurrentResource, error) {
	row := q.db.QueryRow(ctx, getCurrentResourceForUpdate, arg.Cloud, arg.ResourceType, arg.ResourceID)
	var i CurrentResource
	err := row.Scan(
		&i.Cloud,
		&i.Platform,
		&i.ResourceType,
		&i.ResourceID,
		&i.ProjectID,
		&i.State,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.LastEventType,
		&i.LastEventAt,
		&i.LastPayload,
	)
	return i, err
}

const getIngestCredentialByTokenHash = `-- name: GetIngestCredentialByTokenHash :one
SELECT id, platform, cloud, token_hash, description, created_at, revoked_at
FROM ingest_credentials
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetIngestCredentialByTokenHash(ctx context.Context, tokenHash string) (IngestCredential, error) {
	row := q.db.QueryRow(ctx, getIngestCredentialByTokenHash, tokenHash)
	var i IngestCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Cloud,
		&i.TokenHash,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getIngestCredentialForUpdate = `-- name: GetIngestCredentialForUpdate :one
SELECT id, platform, cloud, token_hash, description, created_at, revoked_at
FROM ingest_credentials
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetIngestCredentialForUpdate(ctx context.Context, id uuid.UUID) (IngestCredential, error) {
	row := q.db.QueryRow(ctx, getIngestCredentialForUpdate, id)
	var i IngestCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Cloud,
		&i.TokenHash,
		&i.Description,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getProjectRefsByIDs = `-- name: GetProjectRefsByIDs :many
SELECT id, cloud, external_id
FROM projects
WHERE id = ANY($1::uuid[])
`

type GetProjectRefsByIDsRow struct {
	ID         uuid.UUID
	Cloud      string
	ExternalID string
}

func (q *Queries) GetProjectRefsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetProjectRefsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProjectRefsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectRefsByIDsRow
	for rows.Next() {
		var i GetProjectRefsByIDsRow
		if err := rows.Scan(&i.ID, &i.Cloud, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceType = `-- name: GetResourceType :one
SELECT platform, resource_type, size_schema, updated_at
FROM resource_types
WHERE platform = $1 AND resource_type = $2
`

type GetResourceTypeParams struct {
	Platform     string
	ResourceType string
}

func (q *Queries) GetResourceType(ctx context.Context, arg GetResourceTypeParams) (ResourceType, error) {
	row := q.db.QueryRow(ctx, getResourceType, arg.Platform, arg.ResourceType)
	var i ResourceType
	err := row.Scan(
		&i.Platform,
		&i.ResourceType,
		&i.SizeSchema,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor, action, object_type, object_id, details)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	Actor      string
	Action     string
	ObjectType pgtype.Text
	ObjectID   pgtype.Text
	Details    []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Actor,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Details,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (event_id, timestamp, event_type, platform, cloud,
                    resource_type, resource_id, project_id, source, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (event_id, timestamp) DO NOTHING
RETURNING received_at
`

type InsertEventParams struct {
	EventID      string
	Timestamp    pgtype.Timestamptz
	EventType    string
	Platform     string
	Cloud        string
	ResourceType string
	ResourceID   string
	ProjectID    string
	Source       string
	Payload      []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventID,
		arg.Timestamp,
		arg.EventType,
		arg.Platform,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.ProjectID,
		arg.Source,
		arg.Payload,
	)
	var received_at pgtype.Timestamptz
	err := row.Scan(&received_at)
	return received_at, err
}

const insertRejectedEvent = `-- name: InsertRejectedEvent :exec
INSERT INTO rejected_events (reason, raw)
VALUES ($1, $2)
`

type InsertRejectedEventParams struct {
	Reason string
	Raw    []byte
}

func (q *Queries) InsertRejectedEvent(ctx context.Context, arg InsertRejectedEventParams) error {
	_, err := q.db.Exec(ctx, insertRejectedEvent, arg.Reason, arg.Raw)
	return err
}

const listCurrentResources = `-- name: ListCurrentResources :many
SELECT cloud, platform, resource_type, resource_id, project_id, state, size,
       created_at, deleted_at, last_event_type, last_event_at, last_payload
FROM current_resources
WHERE ($1::text IS NULL OR cloud = $1)
  AND ($2::text IS NULL OR platform = $2)
  AND ($3::text IS NULL OR project_id = $3)
  AND ($4::text IS NULL OR resource_type = $4)
  AND ($5::text IS NULL OR state = $5)
  -- The status filter of the API, as the one boolean the two halves of the
  -- fleet differ in: true serves the deleted rows, false the ones that live,
  -- and NULL both.
  AND ($6::boolean IS NULL OR (state = 'deleted') = $6)
  AND ($7::text[] IS NULL
       OR (cloud, project_id) IN (SELECT unnest($7::text[]),
                                         unnest($8::text[])))
  -- Every bound is cast: inside a row comparison sqlc reads the type of the
  -- later placeholders off the first one, which is why the events cursor above
  -- casts both of its bounds too.
  AND ($9::text IS NULL
       OR (cloud, resource_type, resource_id) > ($9::text,
                                                 $10::text,
                                                 $11::text))
ORDER BY cloud, resource_type, resource_id
LIMIT $12
`

type ListCurrentResourcesParams struct {
	Cloud              pgtype.Text
	Platform           pgtype.Text
	ProjectID          pgtype.Text
	ResourceType       pgtype.Text
	State              pgtype.Text
	Deleted            pgtype.Bool
	ScopeClouds        []string
	ScopeProjects      []string
	CursorCloud        pgtype.Text
	CursorResourceType pgtype.Text
	CursorResourceID   pgtype.Text
	PageSize           int32
}

func (q *Queries) ListCurrentResources(ctx context.Context, arg ListCurrentResourcesParams) ([]CurrentResource, error) {
	rows, err := q.db.Query(ctx, listCurrentResources,
		arg.Cloud,
		arg.Platform,
		arg.ProjectID,
		arg.ResourceType,
		arg.State,
		arg.Deleted,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.CursorCloud,
		arg.CursorResourceType,
		arg.CursorResourceID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentResource
	for rows.Next() {
		var i CurrentResource
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.State,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.LastEventType,
			&i.LastEventAt,
			&i.LastPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT event_id, timestamp, received_at, event_type, platform, cloud,
       resource_type, resource_id, project_id, source, payload
FROM events
WHERE ($1::text IS NULL OR cloud = $1)
  AND ($2::text IS NULL OR platform = $2)
  AND ($3::text IS NULL OR project_id = $3)
  AND ($4::text IS NULL OR resource_type = $4)
  AND ($5::text IS NULL OR event_type = $5)
  AND ($6::text IS NULL OR source = $6)
  AND ($7::timestamptz IS NULL OR timestamp >= $7)
  AND ($8::timestamptz IS NULL OR timestamp < $8)
  AND ($9::text[] IS NULL
       OR (cloud, project_id) IN (SELECT unnest($9::text[]),
                                         unnest($10::text[])))
  -- Both bounds are cast: inside a row comparison sqlc reads the type of the
  -- second placeholder off the first one, which would make the event id a
  -- timestamp in the generated parameters.
  AND ($11::timestamptz IS NULL
       OR (timestamp, event_id) > ($11::timestamptz,
                                   $12::text))
ORDER BY timestamp, event_id
LIMIT $13
`

type ListEventsParams struct {
	Cloud         pgtype.Text
	Platform      pgtype.Text
	ProjectID     pgtype.Text
	ResourceType  pgtype.Text
	EventType     pgtype.Text
	Source        pgtype.Text
	FromTs        pgtype.Timestamptz
	ToTs          pgtype.Timestamptz
	ScopeClouds   []string
	ScopeProjects []string
	CursorTs      pgtype.Timestamptz
	CursorEventID pgtype.Text
	PageSize      int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.Cloud,
		arg.Platform,
		arg.ProjectID,
		arg.ResourceType,
		arg.EventType,
		arg.Source,
		arg.FromTs,
		arg.ToTs,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.CursorTs,
		arg.CursorEventID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.Timestamp,
			&i.ReceivedAt,
			&i.EventType,
			&i.Platform,
			&i.Cloud,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Source,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForResource = `-- name: ListEventsForResource :many
SELECT event_id, timestamp, received_at, event_type, platform, cloud,
       resource_type, resource_id, project_id, source, payload
FROM events
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
  -- The same pair filter the event list runs, per event rather than per
  -- resource: a transfer moves the resource to its new project, and the events
  -- it carried before the transfer stay the old project's alone.
  AND ($4::text[] IS NULL
       OR (cloud, project_id) IN (SELECT unnest($4::text[]),
                                         unnest($5::text[])))
ORDER BY timestamp, received_at, event_id
LIMIT $6
`

type ListEventsForResourceParams struct {
	Cloud         string
	ResourceType  string
	ResourceID    string
	ScopeClouds   []string
	ScopeProjects []string
	PageSize      pgtype.Int4
}

// The history of one resource. Two callers read it: the projection replay, which
// folds every event there is under no scope and no bound, and the two
// per-resource routes of the API, which pass both. A NULL page size is every
// row, which is what the replay folds.
func (q *Queries) ListEventsForResource(ctx context.Context, arg ListEventsForResourceParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForResource,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.ScopeClouds,
		arg.ScopeProjects,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.Timestamp,
			&i.ReceivedAt,
			&i.EventType,
			&i.Platform,
			&i.Cloud,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Source,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceKeys = `-- name: ListResourceKeys :many
SELECT DISTINCT cloud, resource_type, resource_id
FROM events
WHERE ($1::text IS NULL OR cloud = $1)
  AND ($2::text IS NULL OR resource_type = $2)
ORDER BY cloud, resource_type, resource_id
`

type ListResourceKeysParams struct {
	Cloud        pgtype.Text
	ResourceType pgtype.Text
}

type ListResourceKeysRow struct {
	Cloud        string
	ResourceType string
	ResourceID   string
}

func (q *Queries) ListResourceKeys(ctx context.Context, arg ListResourceKeysParams) ([]ListResourceKeysRow, error) {
	rows, err := q.db.Query(ctx, listResourceKeys, arg.Cloud, arg.ResourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceKeysRow
	for rows.Next() {
		var i ListResourceKeysRow
		if err := rows.Scan(&i.Cloud, &i.ResourceType, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceTypes = `-- name: ListResourceTypes :many
SELECT platform, resource_type, size_schema, updated_at
FROM resource_types
ORDER BY platform, resource_type
`

func (q *Queries) ListResourceTypes(ctx context.Context) ([]ResourceType, error) {
	rows, err := q.db.Query(ctx, listResourceTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceType
	for rows.Next() {
		var i ResourceType
		if err := rows.Scan(
			&i.Platform,
			&i.ResourceType,
			&i.SizeSchema,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResource = `-- name: LockResource :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':' || $2::text || ':' || $3::text, 0))
`

type LockResourceParams struct {
	Column1 string
	Column2 string
	Column3 string
}

func (q *Queries) LockResource(ctx context.Context, arg LockResourceParams) error {
	_, err := q.db.Exec(ctx, lockResource, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const revokeIngestCredential = `-- name: RevokeIngestCredential :exec
UPDATE ingest_credentials
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeIngestCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeIngestCredential, id)
	return err
}

const upsertCurrentResource = `-- name: UpsertCurrentResource :exec
INSERT INTO current_resources (cloud, platform, resource_type, resource_id,
                               project_id, state, size, created_at, deleted_at,
                               last_event_type, last_event_at, last_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (cloud, resource_type, resource_id) DO UPDATE
SET platform = EXCLUDED.platform,
    project_id = EXCLUDED.project_id,
    state = EXCLUDED.state,
    size = EXCLUDED.size,
    created_at = EXCLUDED.created_at,
    deleted_at = EXCLUDED.deleted_at,
    last_event_type = EXCLUDED.last_event_type,
    last_event_at = EXCLUDED.last_event_at,
    last_payload = EXCLUDED.last_payload
`

type UpsertCurrentResourceParams struct {
	Cloud         string
	Platform      string
	ResourceType  string
	ResourceID    string
	ProjectID     string
	State         string
	Size          []byte
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	LastEventType string
	LastEventAt   pgtype.Timestamptz
	LastPayload   []byte
}

func (q *Queries) UpsertCurrentResource(ctx context.Context, arg UpsertCurrentResourceParams) error {
	_, err := q.db.Exec(ctx, upsertCurrentResource,
		arg.Cloud,
		arg.Platform,
		arg.ResourceType,
		arg.ResourceID,
		arg.ProjectID,
		arg.State,
		arg.Size,
		arg.CreatedAt,
		arg.DeletedAt,
		arg.LastEventType,
		arg.LastEventAt,
		arg.LastPayload,
	)
	return err
}

const upsertResourceType = `-- name: UpsertResourceType :one
INSERT INTO resource_types (platform, resource_type, size_schema)
VALUES ($1, $2, $3)
ON CONFLICT (platform, resource_type) DO UPDATE
SET size_schema = EXCLUDED.size_schema,
    updated_at = now()
RETURNING platform, resource_type, size_schema, updated_at
`

type UpsertResourceTypeParams struct {
	Platform     string
	ResourceType string
	SizeSchema   []byte
}

func (q *Queries) UpsertResourceType(ctx context.Context, arg UpsertResourceTypeParams) (ResourceType, error) {
	row := q.db.QueryRow(ctx, upsertResourceType, arg.Platform, arg.ResourceType, arg.SizeSchema)
	var i ResourceType
	err := row.Scan(
		&i.Platform,
		&i.ResourceType,
		&i.SizeSchema,
		&i.UpdatedAt,
	)
	return i, err
}
