// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*)
FROM events
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
  AND event_type = $4
  AND timestamp >= $5::timestamptz
  AND timestamp < $6::timestamptz
`

type CountEventsParams struct {
	Cloud        string
	ResourceType string
	ResourceID   string
	EventType    string
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
}

// The events of one type a counter measures inside one usage interval. The
// interval is half-open, [from_ts, to_ts), the same bound the interval itself
// has, and the key carries the cloud and the resource type beside the id
// because an id is unique only within both. idx_events_resource serves the
// predicate on uncompressed chunks; a chunk past the 90-day compression policy
// is segmented by (cloud, resource_type) alone, so the resource id and the
// event type are filtered after decompression, which is what a correction of an
// older period pays.
func (q *Queries) CountEvents(ctx context.Context, arg CountEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.EventType,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCandidates = `-- name: ListCandidates :many
SELECT cloud, platform, resource_type, resource_id
FROM current_resources
WHERE ($1::text[] IS NULL
       OR cloud = ANY($1::text[]))
  AND (deleted_at IS NULL OR deleted_at >= $2::timestamptz)
  AND (created_at IS NULL OR created_at < $3::timestamptz)
ORDER BY cloud, resource_type, resource_id
`

type ListCandidatesParams struct {
	Clouds     []string
	PeriodFrom pgtype.Timestamptz
	PeriodTo   pgtype.Timestamptz
}

type ListCandidatesRow struct {
	Cloud        string
	Platform     string
	ResourceType string
	ResourceID   string
}

// The resources a period can bill. The projection is the index: its rows are
// never deleted, so a resource that lived during the period is still there to
// be found, whatever happened to it since. A NULL cloud list means every cloud.
func (q *Queries) ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]ListCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCandidates, arg.Clouds, arg.PeriodFrom, arg.PeriodTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistory = `-- name: ListHistory :many
SELECT event_id, timestamp, received_at, event_type, platform, cloud,
       resource_type, resource_id, project_id, source, payload
FROM events
WHERE cloud = $1 AND resource_type = $2 AND resource_id = $3
  AND timestamp < $4::timestamptz
ORDER BY timestamp, received_at, event_id
`

type ListHistoryParams struct {
	Cloud        string
	ResourceType string
	ResourceID   string
	PeriodTo     pgtype.Timestamptz
}

// The full history of one candidate up to the period end. The fold starts at
// the first event there is, because the state the resource holds at the period
// start is whatever the events before it left behind.
func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listHistory,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
		arg.PeriodTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.Timestamp,
			&i.ReceivedAt,
			&i.EventType,
			&i.Platform,
			&i.Cloud,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Source,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateEvents = `-- name: ListLateEvents :many
WITH late AS (
    SELECT cloud, platform, resource_type, resource_id,
           count(*)::bigint AS events, max(received_at)::timestamptz AS last_received_at
    FROM events
    WHERE timestamp >= $2::timestamptz
      AND timestamp < $3::timestamptz
      AND received_at > $4::timestamptz
    GROUP BY cloud, platform, resource_type, resource_id
)
SELECT cloud, platform, resource_type, resource_id, events, last_received_at,
       (count(*) OVER ())::bigint AS resources
FROM late
ORDER BY cloud, platform, resource_type, resource_id
LIMIT $1::bigint
`

type ListLateEventsParams struct {
	MaxResources int64
	PeriodFrom   pgtype.Timestamptz
	PeriodTo     pgtype.Timestamptz
	Since        pgtype.Timestamptz
}

type ListLateEventsRow struct {
	Cloud          string
	Platform       string
	ResourceType   string
	ResourceID     string
	Events         int64
	LastReceivedAt pgtype.Timestamptz
	Resources      int64
}

// The late events of one billing period, the detection of WP 3.9
// (roadmap/03-phase-3-metering-rating.md, under "Late-event detection"): the
// events dated inside the period that were received strictly after the instant
// the caller passes, the runs.stats.snapshot_at of the finalized run, grouped
// per resource. The range over timestamp is answered by chunk exclusion, and
// the lower bound on received_at by idx_events_received (reporting migration
// 0009) on the uncompressed chunks; a chunk past the 90-day compression policy
// is segmented by (cloud, resource_type) and ordered by nothing, so its batches
// carry no bounds on received_at and are filtered after decompression, which is
// what detecting the late events of an older period pays.
//
// The groups are bounded by max_resources. A period finalized before its ingest
// had settled has one group per resource of the fleet, and what a caller does
// with the groups is print one line each. The groups the limit cuts off are
// counted all the same: resources is how many arrived late whatever the limit
// let through, and every row carries it, so a caller that read one row knows
// how many it did not.
//
// The strict comparison leaves one window open, and the issue holds it as a
// Non-Goal: an ingest transaction that began before the snapshot and committed
// after it carries a received_at below snapshot_at, so its events are not
// listed here although a correction of the period re-meters them. Ingest
// transactions are milliseconds long, and the window is recorded here rather
// than papered over with a margin.
func (q *Queries) ListLateEvents(ctx context.Context, arg ListLateEventsParams) ([]ListLateEventsRow, error) {
	rows, err := q.db.Query(ctx, listLateEvents,
		arg.MaxResources,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLateEventsRow
	for rows.Next() {
		var i ListLateEventsRow
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
			&i.Events,
			&i.LastReceivedAt,
			&i.Resources,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, platform, cloud, external_id
FROM projects
ORDER BY cloud, external_id
`

type ListProjectsRow struct {
	ID         uuid.UUID
	Platform   string
	Cloud      string
	ExternalID string
}

// The project registry, read whole: attribution walks the graph over these
// UUIDs, and the resources it walks from carry the external id rather than the
// registry's.
func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Cloud,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsOverlapping = `-- name: ListRelationsOverlapping :many
SELECT id, source_id, target_id, relation_type, metadata, valid_from, valid_to
FROM project_relations
WHERE relation_type = ANY($1::text[])
  AND valid_from < $2::timestamptz
  AND (valid_to IS NULL OR valid_to > $3::timestamptz)
ORDER BY id
`

type ListRelationsOverlappingParams struct {
	RelationTypes []string
	PeriodTo      pgtype.Timestamptz
	PeriodFrom    pgtype.Timestamptz
}

type ListRelationsOverlappingRow struct {
	ID           uuid.UUID
	SourceID     uuid.UUID
	TargetID     uuid.UUID
	RelationType string
	Metadata     []byte
	ValidFrom    pgtype.Timestamptz
	ValidTo      pgtype.Timestamptz
}

// The relations that apply to a period, which are the ones whose validity
// overlaps it (D4). A relation closed inside the period still carries the cost
// the period produced before it closed; v1 does not prorate a relation within a
// period.
func (q *Queries) ListRelationsOverlapping(ctx context.Context, arg ListRelationsOverlappingParams) ([]ListRelationsOverlappingRow, error) {
	rows, err := q.db.Query(ctx, listRelationsOverlapping, arg.RelationTypes, arg.PeriodTo, arg.PeriodFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationsOverlappingRow
	for rows.Next() {
		var i ListRelationsOverlappingRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.Metadata,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTime = `-- name: SnapshotTime :one
SELECT now()::timestamptz AS snapshot_at
`

// The first statement of the REPEATABLE READ transaction a run opens. Reading
// now() takes the snapshot every later query in that transaction sees, and the
// value it returns is that snapshot's time, which the run records in
// runs.stats.snapshot_at.
func (q *Queries) SnapshotTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, snapshotTime)
	var snapshot_at pgtype.Timestamptz
	err := row.Scan(&snapshot_at)
	return snapshot_at, err
}
