// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdjustmentRecord struct {
	ID             pgtype.UUID
	RunID          pgtype.UUID
	ProjectID      string
	RelationID     pgtype.UUID
	RelationType   string
	RelationTarget string
	Beneficiary    pgtype.Text
	Type           string
	Scope          string
	Rate           pgtype.Numeric
	Base           pgtype.Numeric
	Amount         pgtype.Numeric
	Currency       string
}

type BillingPeriod struct {
	PeriodFrom     pgtype.Timestamptz
	PeriodTo       pgtype.Timestamptz
	Status         string
	FinalizedRunID pgtype.UUID
	FinalizedAt    pgtype.Timestamptz
}

type CorrectionDelta struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	CorrectsRunID pgtype.UUID
	Cloud         string
	Platform      string
	ResourceType  string
	ResourceID    string
	ProjectID     string
	Dimension     string
	OldAmount     pgtype.Numeric
	NewAmount     pgtype.Numeric
	Delta         pgtype.Numeric
	Currency      string
}

type PricingModel struct {
	Version    string
	ValidFrom  pgtype.Timestamptz
	Currency   string
	Document   []byte
	ImportedAt pgtype.Timestamptz
}

type ProjectStatement struct {
	ID        pgtype.UUID
	RunID     pgtype.UUID
	ProjectID string
	Document  []byte
	Total     pgtype.Numeric
	Currency  string
}

type RatedRecord struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	UsageRecordID pgtype.UUID
	Dimension     string
	Amount        pgtype.Numeric
	Currency      string
}

type Run struct {
	ID             pgtype.UUID
	PeriodFrom     pgtype.Timestamptz
	PeriodTo       pgtype.Timestamptz
	Kind           string
	CorrectsRunID  pgtype.UUID
	PricingVersion pgtype.Text
	Status         string
	Clouds         []string
	Stats          []byte
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type UsageRecord struct {
	ID           pgtype.UUID
	RunID        pgtype.UUID
	Cloud        string
	Platform     string
	ResourceType string
	ResourceID   string
	ProjectID    string
	State        string
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
	Seconds      int64
	Usage        []byte
}
