// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPricingModel = `-- name: GetPricingModel :one
SELECT version, valid_from, currency, imported_at, document
FROM pricing_models
WHERE version = $1
`

type GetPricingModelRow struct {
	Version    string
	ValidFrom  pgtype.Timestamptz
	Currency   string
	ImportedAt pgtype.Timestamptz
	Document   []byte
}

// One pricing version with the catalog document the pricing page renders.
func (q *Queries) GetPricingModel(ctx context.Context, version string) (GetPricingModelRow, error) {
	row := q.db.QueryRow(ctx, getPricingModel, version)
	var i GetPricingModelRow
	err := row.Scan(
		&i.Version,
		&i.ValidFrom,
		&i.Currency,
		&i.ImportedAt,
		&i.Document,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, period_from, period_to, kind, corrects_run_id, pricing_version,
       status, clouds, stats, started_at, completed_at
FROM runs
WHERE id = $1
`

// The header of a run page: the eleven columns a run carries.
func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Kind,
		&i.CorrectsRunID,
		&i.PricingVersion,
		&i.Status,
		&i.Clouds,
		&i.Stats,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getStatement = `-- name: GetStatement :one
SELECT document, total, currency
FROM project_statements
WHERE run_id = $1 AND project_id = $2
`

type GetStatementParams struct {
	RunID     pgtype.UUID
	ProjectID string
}

type GetStatementRow struct {
	Document []byte
	Total    pgtype.Numeric
	Currency string
}

// The statement page: the stored document and the total it sums to.
func (q *Queries) GetStatement(ctx context.Context, arg GetStatementParams) (GetStatementRow, error) {
	row := q.db.QueryRow(ctx, getStatement, arg.RunID, arg.ProjectID)
	var i GetStatementRow
	err := row.Scan(&i.Document, &i.Total, &i.Currency)
	return i, err
}

const latestRunWithResource = `-- name: LatestRunWithResource :one
SELECT r.id
FROM runs r
WHERE EXISTS (
    SELECT 1 FROM usage_records u
    WHERE u.run_id = r.id AND u.cloud = $1 AND u.resource_type = $2 AND u.resource_id = $3
)
ORDER BY r.started_at DESC
LIMIT 1
`

type LatestRunWithResourceParams struct {
	Cloud        string
	ResourceType string
	ResourceID   string
}

// The run a resource page defaults to: the newest run that metered that
// resource at all.
func (q *Queries) LatestRunWithResource(ctx context.Context, arg LatestRunWithResourceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, latestRunWithResource, arg.Cloud, arg.ResourceType, arg.ResourceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCorrectionDeltas = `-- name: ListCorrectionDeltas :many
SELECT cloud, platform, resource_type, resource_id, project_id, dimension,
       old_amount, new_amount, delta, currency
FROM correction_deltas
WHERE run_id = $1
ORDER BY cloud, platform, resource_type, resource_id, project_id, dimension
`

type ListCorrectionDeltasRow struct {
	Cloud        string
	Platform     string
	ResourceType string
	ResourceID   string
	ProjectID    string
	Dimension    string
	OldAmount    pgtype.Numeric
	NewAmount    pgtype.Numeric
	Delta        pgtype.Numeric
	Currency     string
}

// The delta table of a correction run page: what the correction moved, per key.
func (q *Queries) ListCorrectionDeltas(ctx context.Context, runID pgtype.UUID) ([]ListCorrectionDeltasRow, error) {
	rows, err := q.db.Query(ctx, listCorrectionDeltas, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCorrectionDeltasRow
	for rows.Next() {
		var i ListCorrectionDeltasRow
		if err := rows.Scan(
			&i.Cloud,
			&i.Platform,
			&i.ResourceType,
			&i.ResourceID,
			&i.ProjectID,
			&i.Dimension,
			&i.OldAmount,
			&i.NewAmount,
			&i.Delta,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many
SELECT period_from, period_to, status, finalized_run_id, finalized_at
FROM billing_periods
ORDER BY period_from DESC
`

// The period list of the overview page: what months exist, where each one
// stands, and which run closed the finalized ones.
func (q *Queries) ListPeriods(ctx context.Context) ([]BillingPeriod, error) {
	rows, err := q.db.Query(ctx, listPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingPeriod
	for rows.Next() {
		var i BillingPeriod
		if err := rows.Scan(
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Status,
			&i.FinalizedRunID,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingModels = `-- name: ListPricingModels :many
SELECT version, valid_from, currency, imported_at
FROM pricing_models
ORDER BY valid_from DESC
`

type ListPricingModelsRow struct {
	Version    string
	ValidFrom  pgtype.Timestamptz
	Currency   string
	ImportedAt pgtype.Timestamptz
}

// The pricing page's version list, the version in force last first.
func (q *Queries) ListPricingModels(ctx context.Context) ([]ListPricingModelsRow, error) {
	rows, err := q.db.Query(ctx, listPricingModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingModelsRow
	for rows.Next() {
		var i ListPricingModelsRow
		if err := rows.Scan(
			&i.Version,
			&i.ValidFrom,
			&i.Currency,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceSegments = `-- name: ListResourceSegments :many
SELECT u.state, u.from_ts, u.to_ts, u.seconds, u.usage,
       r.dimension, r.amount, r.currency
FROM rated_records r
JOIN usage_records u ON u.id = r.usage_record_id
WHERE r.run_id = $1 AND u.cloud = $2 AND u.resource_type = $3 AND u.resource_id = $4
ORDER BY u.from_ts, r.dimension
`

type ListResourceSegmentsParams struct {
	RunID        pgtype.UUID
	Cloud        string
	ResourceType string
	ResourceID   string
}

type ListResourceSegmentsRow struct {
	State     string
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
	Seconds   int64
	Usage     []byte
	Dimension string
	Amount    pgtype.Numeric
	Currency  string
}

// The timeline of a resource page: every metered segment of one run with the
// amounts it was rated at.
func (q *Queries) ListResourceSegments(ctx context.Context, arg ListResourceSegmentsParams) ([]ListResourceSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listResourceSegments,
		arg.RunID,
		arg.Cloud,
		arg.ResourceType,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceSegmentsRow
	for rows.Next() {
		var i ListResourceSegmentsRow
		if err := rows.Scan(
			&i.State,
			&i.FromTs,
			&i.ToTs,
			&i.Seconds,
			&i.Usage,
			&i.Dimension,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, period_from, period_to, kind, corrects_run_id, pricing_version,
       status, clouds, stats, started_at, completed_at
FROM runs
ORDER BY started_at DESC
LIMIT $1
`

// The run list of the overview page, newest first and bounded by the caller.
func (q *Queries) ListRuns(ctx context.Context, limit int32) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Kind,
			&i.CorrectsRunID,
			&i.PricingVersion,
			&i.Status,
			&i.Clouds,
			&i.Stats,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatements = `-- name: ListStatements :many
SELECT project_id, total, currency
FROM project_statements
WHERE run_id = $1
ORDER BY total DESC, project_id
`

type ListStatementsRow struct {
	ProjectID string
	Total     pgtype.Numeric
	Currency  string
}

// The statement table of a run page, largest total first. The project key
// breaks a tie between two equal totals, so the page renders one order.
func (q *Queries) ListStatements(ctx context.Context, runID pgtype.UUID) ([]ListStatementsRow, error) {
	rows, err := q.db.Query(ctx, listStatements, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsRow
	for rows.Next() {
		var i ListStatementsRow
		if err := rows.Scan(&i.ProjectID, &i.Total, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementsForProject = `-- name: ListStatementsForProject :many
SELECT s.run_id, r.period_from, r.kind, r.status, s.total, s.currency
FROM project_statements s
JOIN runs r ON r.id = s.run_id
WHERE s.project_id = $1
ORDER BY r.period_from, r.started_at
`

type ListStatementsForProjectRow struct {
	RunID      pgtype.UUID
	PeriodFrom pgtype.Timestamptz
	Kind       string
	Status     string
	Total      pgtype.Numeric
	Currency   string
}

// The history of one project across runs, oldest month first.
func (q *Queries) ListStatementsForProject(ctx context.Context, projectID string) ([]ListStatementsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listStatementsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsForProjectRow
	for rows.Next() {
		var i ListStatementsForProjectRow
		if err := rows.Scan(
			&i.RunID,
			&i.PeriodFrom,
			&i.Kind,
			&i.Status,
			&i.Total,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
