// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Problem RFC 9457 problem detail. Every error response in this API uses this shape, served as application/problem+json.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Per-field details, set when the problem is a validation failure.
	Errors *[]struct {
		// Loc Location of the offending value, e.g. body.resource_id.
		Loc string `json:"loc"`

		// Msg What is wrong with the value at that location.
		Msg string `json:"msg"`
	} `json:"errors,omitempty"`

	// Status The HTTP status code of this response.
	//
	// Example: 400
	Status int `json:"status"`

	// Title Short human-readable summary of the problem type.
	//
	// Example: Validation failed
	Title string `json:"title"`

	// Type URI reference identifying the problem type.
	//
	// Example: urn:tally:error:validation
	Type string `json:"type"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Readyz Readiness probe
	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Healthz Liveness probe
// (GET /healthz)
func (_ Unimplemented) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readyz Readiness probe
// (GET /readyz)
func (_ Unimplemented) Readyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readyz)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fbfbxs3DP5XiNve5tje0mKY+9R1HRpgD0Ga/QC2YWUk3p0aWVIpnt1rkf99oHS248TbUGDAsLezxeNH",
	"ft8n8j42Jq5TDBQkN6uPTU9oicvjFb0bKMvFd/rDUjbskrgYmlXzIjKTR/0FzkJsQXqXgesbc7juCTLx",
	"hhjQxiQZpCeIgQDBoPfEkCnYDBgsdBSIUSiXgCg98dZlegZOAFMiZD0B2hCP4GMH3mlcW3JOkDPIEd4N",
	"UVzo9D0XACEPKUWWXQy4DNseBcRRLUi2ESR2pJDzZtZk09MatV0ZEzWrJgu70DV3d3ezhimnGDIVbi45",
	"3nha66OJQSiIPmJK3plCyyLViC/eZmXs473cnzO1zar5bHFgflFP82KXtyAec3596BZadJ5s5fkm2hEy",
	"jhn6uNUu7kn4y9kk4llV8RT0FL44yH1X0KeSHnR7XNPV9y/gmydPv4apW7Ak6PwcXhaxiDky7IhTUYpN",
	"nl9ewJCLBi5D7jHRrNrFAmb4Kxa1t8QxEauAtRhFe1zWq2GN4YwJLd54AnqfPIbq1pzIuNYZkFjhozED",
	"MwVDmv+B7rOmtJAfQ1wSn7WOvJ1aztqBwLanUKy1I8RlQNigd7biq3IDFywntC6Zj5vy0TyG+yFWQna2",
	"j21LwarZN+gHmgHNu3mxwpwpx4EN/eHsyY7WuXuc/2e9F3o/OIYOtk76AlOSg14ZPfdTESfSlvvxbnBM",
	"tln9WnqoSL/vQ+PNWzKiFUx/IDOO+jsLynCCY3X3q+vrS6gBYKKle7OmukqLofe4Tp6a1ZPlcp/eBaGO",
	"uAA60dOH+V/3Oh36Y7PkYb1GHndE73TUpEdQzU/HopI9RXb94yHwj1cXwNRSsR04S0FcO6qafw85cFgJ",
	"ej+uii1XB1/9oyLldMfEnvLH6qgcZAZ2Mr7WAVA9eUPIxM8H6U+wSLxxhkDiLQVImHO9xm80PLL7UApc",
	"wbclB/w2LJfnpgSXR3qzn7xaR0U6tNOLpDoNXWjjY/SXGwo67jvK+s8MdvYHF/Qo8jgrW2bI2OkA1Y2g",
	"TLeR4Vq51CnqMthohrXmquNA/AgmbojrpugJvfRAwaboguRn0/KpWDNdTkEq0AFiHw3I7Da0v1eOYRv5",
	"FhKaW+woz/fKrJpSE1ztkzy/vGhmjRZSG17Ov5wv1VoxUcDkmlVzPl/Oz3U4ovRFrkUt94M+dyQn5nZJ",
	"r+uw7L6d7Qxlncdx8BZuiRLwEIIL3Rwu6s7RRexHwFaml/Ikfo8ZbogCDKFij4VgH0NXIrFORRND67qB",
	"yYL0TLmP3pbVXeYLgjCG7FQFi4I3mAniIFW4LKglhyi9ltQUBriY68Lq0J96frCpv1ouH2xpofeySB7d",
	"g718uGfx9sR9OrmQd/3rmPduQ//W/p01T2vdp97Y93f4XND480+I12teB50uF7ehoNLr5KFyuNB5OH6a",
	"gXZcGAx1m6ucbevMPftse+epRO8FdhmGwISm1/k70xDTg+Dt9JGWolUT6EDmKHXg6kXS/yZX1I++x5a4",
	"qk38V44oHOqHxjEb/0eLKJPuyCN3d38GAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
