// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ListEventsParamsSource.
const (
	Collector      ListEventsParamsSource = "collector"
	Reconciliation ListEventsParamsSource = "reconciliation"
)

// Valid indicates whether the value is a known member of the ListEventsParamsSource enum.
func (e ListEventsParamsSource) Valid() bool {
	switch e {
	case Collector:
		return true
	case Reconciliation:
		return true
	default:
		return false
	}
}

// EventInput One canonical event. The members below are described rather than constrained; the normative schema is roadmap/00-conventions.md section 4.
type EventInput struct {
	// Cloud The installation the resource lives in, os-prod-eu1 for example.
	Cloud interface{} `json:"cloud,omitempty"`

	// EventId Globally unique idempotency key of 1 to 256 characters. An event id resubmitted with the same timestamp counts as a duplicate.
	EventId interface{} `json:"event_id,omitempty"`

	// EventType What happened, written resource.action with an optional phase, for example compute.instance.create.end.
	EventType interface{} `json:"event_type,omitempty"`

	// Payload The normalized payload envelope: the state at or after the event, the full replacement size when it changed, and optional raw provider data.
	Payload interface{} `json:"payload,omitempty"`

	// Platform The platform the resource lives on, openstack for example.
	Platform interface{} `json:"platform,omitempty"`

	// ProjectId The project owning the resource at or after this event.
	ProjectId interface{} `json:"project_id,omitempty"`

	// ResourceId The resource this event is about.
	ResourceId interface{} `json:"resource_id,omitempty"`

	// ResourceType The kind of resource, instance or volume for example.
	ResourceType interface{} `json:"resource_type,omitempty"`

	// Source Where the event came from. The stored event always reports the pipeline that ingested it, so a collector cannot mark its events as reconciliation output. The member may be left out; a value outside `collector` and `reconciliation` refuses the item.
	Source interface{} `json:"source,omitempty"`

	// Timestamp When the event happened, ISO 8601 with a timezone.
	Timestamp            interface{}            `json:"timestamp,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// EventList One page of stored events.
type EventList struct {
	// Items The events of this page, ordered by timestamp and event id.
	Items []StoredEvent `json:"items"`

	// NextCursor Where the next page starts, passed back as `cursor`. It is null on the last page.
	NextCursor *string `json:"next_cursor"`
}

// IngestResult What one ingest call did with the batch it was given.
type IngestResult struct {
	// Accepted How many events the call stored.
	Accepted int `json:"accepted"`

	// Duplicates How many items the database already held.
	Duplicates int `json:"duplicates"`

	// Rejected The items the call refused, one entry each.
	Rejected []RejectedEvent `json:"rejected"`
}

// Problem RFC 9457 problem detail. Every error response in this API uses this shape, served as application/problem+json.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Per-field details, set when the problem is a validation failure.
	Errors *[]struct {
		// Loc Location of the offending value, e.g. body.resource_id.
		Loc string `json:"loc"`

		// Msg What is wrong with the value at that location.
		Msg string `json:"msg"`
	} `json:"errors,omitempty"`

	// Status The HTTP status code of this response.
	//
	// Example: 400
	Status int `json:"status"`

	// Title Short human-readable summary of the problem type.
	//
	// Example: Validation failed
	Title string `json:"title"`

	// Type URI reference identifying the problem type.
	//
	// Example: urn:tally:error:validation
	Type string `json:"type"`
}

// RebuildRequest Which resources to replay. A member left out filters nothing, so an empty object rebuilds every resource the events table knows.
type RebuildRequest struct {
	// Cloud Replay only the resources of this cloud.
	Cloud *string `json:"cloud,omitempty"`

	// ResourceType Replay only the resources of this type.
	ResourceType *string `json:"resource_type,omitempty"`
}

// RebuildResult What one rebuild replayed.
type RebuildResult struct {
	// Rebuilt How many resources were replayed.
	Rebuilt int `json:"rebuilt"`
}

// RegisterResourceType The size schema to register for a resource type.
type RegisterResourceType struct {
	// SizeSchema A JSON Schema draft 2020-12 document. It is compiled before it is stored, so the document a registration accepts is exactly the one ingestion can apply later.
	SizeSchema map[string]interface{} `json:"size_schema"`
}

// RejectedEvent One refused item and the reason it was refused.
type RejectedEvent struct {
	// EventId The event id the item carried. It is the empty string for an item that carried none, which is why the index is what identifies the item.
	EventId string `json:"event_id"`

	// Index The item's position in the submitted batch, counted from zero.
	Index int `json:"index"`

	// Reason Why the item was refused, for example "size_schema: 'vcpus' is a required property".
	Reason string `json:"reason"`
}

// ResourceType One registered resource type and the size schema the sizes reported for it are validated against.
type ResourceType struct {
	// Platform The platform the resource type belongs to.
	Platform string `json:"platform"`

	// ResourceType The resource type within that platform.
	ResourceType string `json:"resource_type"`

	// SizeSchema The registered JSON Schema draft 2020-12 document.
	SizeSchema map[string]interface{} `json:"size_schema"`

	// UpdatedAt When the schema was last written.
	UpdatedAt time.Time `json:"updated_at"`
}

// ResourceTypeList The registered resource types.
type ResourceTypeList struct {
	// Items The resource types, ordered by platform and resource type.
	Items []ResourceType `json:"items"`

	// NextCursor Where the next page starts. It is always null today: the registry holds one row per resource type, so every registration fits into one answer. Cursor pagination arrives with the query endpoints.
	NextCursor *string `json:"next_cursor"`
}

// StoredEvent One event as the events table holds it: what was submitted, plus the instant this API stored it.
type StoredEvent struct {
	// Cloud The installation the resource lives in.
	Cloud string `json:"cloud"`

	// EventId The idempotency key the event was submitted under.
	EventId string `json:"event_id"`

	// EventType What happened, written resource.action with an optional phase, for example compute.instance.create.end.
	EventType string `json:"event_type"`

	// Payload The normalized payload envelope, member for member as it was stored. It is null for an event stored without one, which a delete event may be. The members are not constrained here: an envelope keeps the fields a provider sent beyond the ones this API names.
	Payload *map[string]interface{} `json:"payload"`

	// Platform The platform the resource lives on.
	Platform string `json:"platform"`

	// ProjectId The project owning the resource at or after this event.
	ProjectId string `json:"project_id"`

	// ReceivedAt When this API stored the event.
	ReceivedAt time.Time `json:"received_at"`

	// ResourceId The resource the event is about.
	ResourceId string `json:"resource_id"`

	// ResourceType The kind of resource the event is about.
	ResourceType string `json:"resource_type"`

	// Source Which pipeline produced the event, collector or reconciliation. It is what the server recorded rather than what the submitter claimed.
	Source string `json:"source"`

	// Timestamp When the event happened.
	Timestamp time.Time `json:"timestamp"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	// Cloud Serve only the events of this cloud.
	Cloud *string `form:"cloud,omitempty" json:"cloud,omitempty"`

	// Platform Serve only the events of this platform.
	Platform *string `form:"platform,omitempty" json:"platform,omitempty"`

	// ProjectId Serve only the events of this project, named the way its cloud names it. A token asking for a project outside its scope is answered 403.
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`

	// ResourceType Serve only the events about resources of this type.
	ResourceType *string `form:"resource_type,omitempty" json:"resource_type,omitempty"`

	// EventType Serve only the events of this type, volume.create for example.
	EventType *string `form:"event_type,omitempty" json:"event_type,omitempty"`

	// Source Serve only the events the named pipeline produced.
	Source *ListEventsParamsSource `form:"source,omitempty" json:"source,omitempty"`

	// From Serve only the events at or after this instant, the inclusive bound of the window.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Serve only the events before this instant, the exclusive bound of the window.
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Limit How many events one page carries at most.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the page before this one. It is opaque: a client passes it back as it received it and reads nothing out of it.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListEventsParamsSource defines parameters for ListEvents.
type ListEventsParamsSource string

// IngestEventsJSONBody defines parameters for IngestEvents.
type IngestEventsJSONBody struct {
	union json.RawMessage
}

// IngestEventsJSONBody1 defines parameters for IngestEvents.
type IngestEventsJSONBody1 = []EventInput

// IngestEventsJSONRequestBody defines body for IngestEvents for application/json ContentType.
type IngestEventsJSONRequestBody IngestEventsJSONBody

// PutResourceTypeJSONRequestBody defines body for PutResourceType for application/json ContentType.
type PutResourceTypeJSONRequestBody = RegisterResourceType

// RebuildProjectionJSONRequestBody defines body for RebuildProjection for application/json ContentType.
type RebuildProjectionJSONRequestBody = RebuildRequest

// Getter for additional properties for EventInput. Returns the specified
// element and whether it was found
func (a EventInput) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for EventInput
func (a *EventInput) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for EventInput to handle AdditionalProperties
func (a *EventInput) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cloud"]; found {
		err = json.Unmarshal(raw, &a.Cloud)
		if err != nil {
			return fmt.Errorf("error reading 'cloud': %w", err)
		}
		delete(object, "cloud")
	}

	if raw, found := object["event_id"]; found {
		err = json.Unmarshal(raw, &a.EventId)
		if err != nil {
			return fmt.Errorf("error reading 'event_id': %w", err)
		}
		delete(object, "event_id")
	}

	if raw, found := object["event_type"]; found {
		err = json.Unmarshal(raw, &a.EventType)
		if err != nil {
			return fmt.Errorf("error reading 'event_type': %w", err)
		}
		delete(object, "event_type")
	}

	if raw, found := object["payload"]; found {
		err = json.Unmarshal(raw, &a.Payload)
		if err != nil {
			return fmt.Errorf("error reading 'payload': %w", err)
		}
		delete(object, "payload")
	}

	if raw, found := object["platform"]; found {
		err = json.Unmarshal(raw, &a.Platform)
		if err != nil {
			return fmt.Errorf("error reading 'platform': %w", err)
		}
		delete(object, "platform")
	}

	if raw, found := object["project_id"]; found {
		err = json.Unmarshal(raw, &a.ProjectId)
		if err != nil {
			return fmt.Errorf("error reading 'project_id': %w", err)
		}
		delete(object, "project_id")
	}

	if raw, found := object["resource_id"]; found {
		err = json.Unmarshal(raw, &a.ResourceId)
		if err != nil {
			return fmt.Errorf("error reading 'resource_id': %w", err)
		}
		delete(object, "resource_id")
	}

	if raw, found := object["resource_type"]; found {
		err = json.Unmarshal(raw, &a.ResourceType)
		if err != nil {
			return fmt.Errorf("error reading 'resource_type': %w", err)
		}
		delete(object, "resource_type")
	}

	if raw, found := object["source"]; found {
		err = json.Unmarshal(raw, &a.Source)
		if err != nil {
			return fmt.Errorf("error reading 'source': %w", err)
		}
		delete(object, "source")
	}

	if raw, found := object["timestamp"]; found {
		err = json.Unmarshal(raw, &a.Timestamp)
		if err != nil {
			return fmt.Errorf("error reading 'timestamp': %w", err)
		}
		delete(object, "timestamp")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for EventInput to handle AdditionalProperties
func (a EventInput) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["cloud"], err = json.Marshal(a.Cloud)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cloud': %w", err)
	}

	object["event_id"], err = json.Marshal(a.EventId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event_id': %w", err)
	}

	object["event_type"], err = json.Marshal(a.EventType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event_type': %w", err)
	}

	object["payload"], err = json.Marshal(a.Payload)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'payload': %w", err)
	}

	object["platform"], err = json.Marshal(a.Platform)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'platform': %w", err)
	}

	object["project_id"], err = json.Marshal(a.ProjectId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'project_id': %w", err)
	}

	object["resource_id"], err = json.Marshal(a.ResourceId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'resource_id': %w", err)
	}

	object["resource_type"], err = json.Marshal(a.ResourceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'resource_type': %w", err)
	}

	object["source"], err = json.Marshal(a.Source)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'source': %w", err)
	}

	object["timestamp"], err = json.Marshal(a.Timestamp)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'timestamp': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsEventInput returns the union data inside the IngestEventsJSONBody as a EventInput
func (t IngestEventsJSONBody) AsEventInput() (EventInput, error) {
	var body EventInput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventInput overwrites any union data inside the IngestEventsJSONBody as the provided EventInput
func (t *IngestEventsJSONBody) FromEventInput(v EventInput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventInput performs a merge with any union data inside the IngestEventsJSONBody, using the provided EventInput
func (t *IngestEventsJSONBody) MergeEventInput(v EventInput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIngestEventsJSONBody1 returns the union data inside the IngestEventsJSONBody as a IngestEventsJSONBody1
func (t IngestEventsJSONBody) AsIngestEventsJSONBody1() (IngestEventsJSONBody1, error) {
	var body IngestEventsJSONBody1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIngestEventsJSONBody1 overwrites any union data inside the IngestEventsJSONBody as the provided IngestEventsJSONBody1
func (t *IngestEventsJSONBody) FromIngestEventsJSONBody1(v IngestEventsJSONBody1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIngestEventsJSONBody1 performs a merge with any union data inside the IngestEventsJSONBody, using the provided IngestEventsJSONBody1
func (t *IngestEventsJSONBody) MergeIngestEventsJSONBody1(v IngestEventsJSONBody1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IngestEventsJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *IngestEventsJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListEvents List stored events
	// (GET /api/v1/events)
	ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams)
	// IngestEvents Ingest events
	// (POST /api/v1/events)
	IngestEvents(w http.ResponseWriter, r *http.Request)
	// ListResourceTypes List the registered resource types
	// (GET /api/v1/resource-types)
	ListResourceTypes(w http.ResponseWriter, r *http.Request)
	// GetResourceType Read one registered resource type
	// (GET /api/v1/resource-types/{platform}/{resource_type})
	GetResourceType(w http.ResponseWriter, r *http.Request, platform string, resourceType string)
	// PutResourceType Register a resource type
	// (PUT /api/v1/resource-types/{platform}/{resource_type})
	PutResourceType(w http.ResponseWriter, r *http.Request, platform string, resourceType string)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// RebuildProjection Rebuild the projection
	// (POST /internal/projection/rebuild)
	RebuildProjection(w http.ResponseWriter, r *http.Request)
	// Readyz Readiness probe
	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListEvents List stored events
// (GET /api/v1/events)
func (_ Unimplemented) ListEvents(w http.ResponseWriter, r *http.Request, params ListEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// IngestEvents Ingest events
// (POST /api/v1/events)
func (_ Unimplemented) IngestEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListResourceTypes List the registered resource types
// (GET /api/v1/resource-types)
func (_ Unimplemented) ListResourceTypes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetResourceType Read one registered resource type
// (GET /api/v1/resource-types/{platform}/{resource_type})
func (_ Unimplemented) GetResourceType(w http.ResponseWriter, r *http.Request, platform string, resourceType string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PutResourceType Register a resource type
// (PUT /api/v1/resource-types/{platform}/{resource_type})
func (_ Unimplemented) PutResourceType(w http.ResponseWriter, r *http.Request, platform string, resourceType string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Healthz Liveness probe
// (GET /healthz)
func (_ Unimplemented) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RebuildProjection Rebuild the projection
// (POST /internal/projection/rebuild)
func (_ Unimplemented) RebuildProjection(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readyz Readiness probe
// (GET /readyz)
func (_ Unimplemented) Readyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "cloud" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cloud", r.URL.Query(), &params.Cloud, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cloud"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cloud", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "platform", r.URL.Query(), &params.Platform, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "platform"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "project_id", r.URL.Query(), &params.ProjectId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "project_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "resource_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resource_type", r.URL.Query(), &params.ResourceType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "event_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "event_type", r.URL.Query(), &params.EventType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "event_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "event_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestEvents operation middleware
func (siw *ServerInterfaceWrapper) IngestEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListResourceTypes operation middleware
func (siw *ServerInterfaceWrapper) ListResourceTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListResourceTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetResourceType operation middleware
func (siw *ServerInterfaceWrapper) GetResourceType(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "platform" -------------
	var platform string

	err = runtime.BindStyledParameterWithOptions("simple", "platform", chi.URLParam(r, "platform"), &platform, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Path parameter "resource_type" -------------
	var resourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "resource_type", chi.URLParam(r, "resource_type"), &resourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource_type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetResourceType(w, r, platform, resourceType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutResourceType operation middleware
func (siw *ServerInterfaceWrapper) PutResourceType(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "platform" -------------
	var platform string

	err = runtime.BindStyledParameterWithOptions("simple", "platform", chi.URLParam(r, "platform"), &platform, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Path parameter "resource_type" -------------
	var resourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "resource_type", chi.URLParam(r, "resource_type"), &resourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource_type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutResourceType(w, r, platform, resourceType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RebuildProjection operation middleware
func (siw *ServerInterfaceWrapper) RebuildProjection(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RebuildProjection(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/events", wrapper.ListEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/events", wrapper.IngestEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/resource-types", wrapper.ListResourceTypes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/resource-types/{platform}/{resource_type}", wrapper.GetResourceType)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/resource-types/{platform}/{resource_type}", wrapper.PutResourceType)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/internal/projection/rebuild", wrapper.RebuildProjection)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Ft7j9tIcv8qBSXA3iIajcZrXxL5L9/GuZ1gkTXGzgNYG1aLLIl9Q3bT3c2RZWO+e1BV3XxIlOaxtvc2",
	"/3kssrve9asHP08yW9XWoAl+svg8KVDl6PifV/ihQR8u/43+yNFnTtdBWzNZTH60zmGp6C/QOdg1hEJ7",
	"cPLGDN4UCB7dDTpQua2Dh1AgWIOgIFNliQ48mtyDMjls0KBTAT0/YEOBbqs9PgcdQNU1Kke/AN6g20Fp",
	"N1Bqem7NZ8Yrp+AtfGhs0GZD72kDCnxT19aF9AxoD9tCBQgahaCwtRDsBunK2WQ68VmBlSJ2w67GyWLi",
	"g9NmM7m9vZ1OHPraGo8sm1fOrkqs6J+ZNQFNoH+qui51xmI5r+WJf/qbJ4l97p39jw7Xk8XkH847yZ/L",
	"r/48ncs3DmX+puMW1kqXmIucVzbfgVc7D4XdEhc9Ff7vWVTimWhx7Or4+Hmn7lu+PZJEr728QRMuTd0I",
	"l3muiSZVvnK2RkfinCyCa3Cf5F8MQqaMNTpTJSnQRNuosFqh87DC0m5BOQR5cYU5OEXqgFAoA5k1Pjil",
	"DebPWWPGukoFfYMg5JFOnVV5perz+fwss4Yu0db4WZWDx4xN9CmJpe4R+3mSlbbJDw2biNPGB1VG6xYb",
	"87ZxGUKpb9CDNlOw/qx2Nj/D5gLW1gF+VFVd4mxyO50wn+/1yOl/Le1KleUOGqM/NAg6x6q2AU22g2vc",
	"kU1fQLDw5NmfISuUU1lA52fwwojwyNcc+mZV6RAwh60OBVPoVYUQdIU+qKqGzDYmeFAeFOSN2GSfNrHu",
	"fer+h3yjII8zmE9h6+gS03I/UyJMvlQZsLUYAdSF8jjtiwHIvJqAMxalyXCWOSQS0ORMRq12pVVH5M86",
	"LvUnzCE+B2husLQ1LoTboAKCCmAdqHVgY0GR0JT/uW7KEhzWpcqwIrl5/QlhW6Ch2JAVymyIQwo+LRdO",
	"baF29kbn6CBXQQmhpQpr66pxStOvY1ZiyUpqJAFk1wc2Ujv7N8zGrYRPlt/Bbg1FtMH5Q8a1j441kRjF",
	"zxw9tz2ke5FcSK1ss3fCuI3QGdfacMhPj04hqZnourFlU+EBw/LomNGhw05/kJElr52tYhIJ1mEef1Pl",
	"lsKcQ4rqEsFrXSOng0DGq80GPTmGloSgILNliVmwjuKQsQEq5a5Bh8g7+4jDzJpMl1o83jahbgZxCiq1",
	"gxVCietAPz8HBTeqbJD+8DpHWLb3LNmqlsMzl+Bw3fiYdXTAimXSOuyoWExPKp1XXr7+Bf7lz/OL6Ibs",
	"9J+sISHTiZK27IqMh67gyP2z9uHwCgrOtdpwJu2L2R8GS6LYjxtDFGNCAHTgFKzLkc5b7XpBieSSohhd",
	"0R56Kh++ZsKYi0nHn3JO7ehvgx/D+6xx3rpTpkWPCa8+KBf8FGrlPRFIvqk8LOWM5Qwu2R8MBZAY/Uvl",
	"5WUimn5QqxJTvtvHCeRAHxrtMJ8sfo0sDsl8N6KlS7bbK/RNGY7EZYJGYt4MoCDXvfC/UiErKLRtlYeN",
	"vkFzqEOVZVgHHIkLP9ktVMrski7pRL5DrIKOihRrE3CDjkhu04o/cSDzz+dRQF0pj6BKhyrfQYHlkZMd",
	"kljwWHJuj2QSxa/yKcsHTXA7QJUV97avq3jZEQvb02crwwH/PZLHlNuDikN2rv79R/jXp8/+GSJUhByD",
	"0uUMXjLSReesg4Q6CdGyh714dQkxlGgPvlA1TgVr55zwj0DQQ4OQ20a011TKnJGWyNABP9alMhIafY2Z",
	"XuuMMApfb7OscQ4pw08OnGE6YRZGDOQVurO1xjKPLHviIEiCDpL9WCCUmSjS6lzuJ9jbOBxod8hUabPD",
	"6362WQztUjPY9RpNTnmVo/gUcLaZMY6e9RLoKEeV3xxxUCounDWbzislRVC9Qb+XkYiRY/esjHiQm8bM",
	"aT8EEhhqjgTnn968eQXyAGQ2x16hJlZFxMQsPVk8nc/H/DHoUI4k7tcFlVbF0Fh8U1XK7ZKgkx7p0MFV",
	"k/8eKpVd6kDY4xDkv64uye2RzY4gtAl6vUso6fiVjTMLwvW7BZvlorOrOzXCvyZJtCIf084Vrhpd5rGW",
	"GjMVnRUtcvLkSIxTdzN4kdBGghmw1iXhfzA2FNpsBNIYwKoOO5A7wcmFPpbHPXzX5ubAqrk2duvvXQdd",
	"MVFgTbkbgM8u0/OLoz5yB4S8++iku0OlHJf3HakziikKW5LaUBDyRDiRzTpCtwQs+kfte82e/aSzxy1m",
	"o31AdxVPf3MUd3MRE8tetht5kaG26mk+Sm/IHr38vutBDE9/Af/x+pf/hNdydu7UOsCT+ZP52cUTyG3W",
	"VFy4CzSiJEoOCytcW4fcbPERKrCFcrqPLzFdRKYTX5cE6ukN/KiyEE2gAzf0UKYMp7EdlCpIY2ZPanvi",
	"7fM2LuJ+kh8FwhFHMLxgpCqWqbw1CVfFRw5Fe7zebwEyFe4J+kOmnNOYJ4Gyp7JLi6GLPo08y6kjvgDG",
	"GpzClkMI97JEetrk+LFtbsWAqAfFxoiX8lvHMdZ3HmrrtXT4JCt3fQfGm1NpM2DO5Rp8QmePAToVe2D7",
	"zrnrhNKT8LCV8Lav3gV8d5PVjf9OoEEyAogK2b2d3J1ehfFem6alcNx2TrmlmI74IeZDH2zNaOC38e9U",
	"xZL0rONOp8MEdQjJbRQV1YfG9piGBFOzwtKaDWWcxwTtNwfnEcxhw1ChvXb05JORR85tBXiPMDQZUVJT",
	"s9Teq3Ciko4aIEPjki72t+jANXcVJ4sJHXNGJeudVtTqYV90Q4YHtN1lX+N1+p6IBlp4WK0+fHVQpreG",
	"Q0Z7kEruWUr1POXL1eopTMbmD1fmweZqt4hGzullB4UlFMS53m6hRjdkg1NTwki9jLTWlI5MsDKdMH6L",
	"bgY/MplEho6lD4XgG0r9Cd1/aLhIM3ltdWyafJ3mQL8FMhqAYnPMH2I+kYkOC0kNZPptEJ9CXTYxR3D7",
	"LnT1ZWwH6fCF++bjReLJ9LnfIu96YgNuoDH5ACrsn//7trxHyHpsC3yaygS6PP5T+QRSYsum38aKcEKE",
	"FjVLDFGF0QMUCnIsMSTpSstzOK2hFGVs6E9lgPx2wedH+uAasRa74hKf8nTbV/d09Ap3NqZGa1Ijg8zO",
	"qApPOVLnE7+lLT+uja/Qjx/Nshnqm9OZauiDrb3fN089bAiABzOAx2GD/ZnAfY8+PhYgm2y7+7WzeZP1",
	"xTHttfa5Tdbvtyf7l2lvN4ump1y+N2PsHorBxEFWKl3huN8+vGn/SITRw6fdnYNwNu2jEAnMh2ikbw0D",
	"O2+F38WioYG+G6u7PGaN02HHIC12lmv9xl7jCMJ/YdiUA/2aWu7Kw/JFEwrr9CdW1gL+gsqhg7fNfP5D",
	"xg/zP3E5g5cqK4Dyj2QVjhDifbbk2tMg5v45qHiJDJSlJpVkjjk8nf/QTveJnRXf1ymgCKGWkohK0OO8",
	"pP67Q66xVDkF7X1DQRod/CkpYyq9ke8ZSz2K60uJv1IipJROcVzQttIOVMlDn3txFdAZVR7hizsLhSI5",
	"ecwcii/wFga84WF1h/Wk5y6QQQ4FZ5sQYdH00cxq7nElYQYLdbMqdRZXRfw92LxlRtf2kL+XEoRSd2Ha",
	"hSjNuwLW7WQS3HgCnSLzVIazACgJat/1NDJ7Q9mQxFCgKkPBTUcC1Lh/Vz9PnHHZlPDqtC0Po0uSeccu",
	"1fMewBQ8nmhq4WbEoy0c1Q621l1DrbJrtZEsGhu3E9HiVXvIi1eXk+mEeBAJzWcXszlZiq3RqFpPFpMf",
	"ZvPZDxwYQsE+fq5qfX5zcS62SP+zwTDW2wuNM6kZ2Z8qTsEo5+xWyg2GHPRQ2+Ps7fLEfocX8MFFClnI",
	"8k9tGIySfq/z75egfCbd/Bks185WcQIb7BI8UoYQTalyfUYMwlab3G5h+Ss9PIVgv1+mUZ/or71m0eEm",
	"FdqGVbxE+zh1kdlT/wG6Wkx69tbIDkxZxnAkJQqPE2HJJcAy8dvD72Idy15psBzkMy6S+FR2Od+fYVIw",
	"ZOB38Dqfb/LUnd+q8lpkLM/EckF1jR8iIjafAUsvRVTtkGBcXLRK61NiiRI2kk6JYixLyHFNWHERQaH8",
	"yESoyIW0+7iPJCEuUWDNVrncz94a9sFSyxoXS+nMZ7beS+ats8lvM3jRQjdJEA5V2yyPdURhPcKyy4zL",
	"mGasbJlRgRh/9FPQJiubPGHAtETQBZXUq+u6owTLg1PGr9GRO6it2onYa3Rn7YtCWI6ZzjHZY0v6Xpiw",
	"25QJqRBOXVd2uJqt8gCjBunL2jLvoKyJMC0R1/VxKXq0SfcynywmP2sfXorvU1RwqsLAO2a/HsyFyCm6",
	"7v7efkA7NdD0LIc4wvuKQ3uCMMfX8KYPu63flxq7sAefvtydIt4payiPjrZjK2L+ouZ0INsUm1T+uu37",
	"duqJqyX0IhvzGKQZZWoA8X4rWwzdT8xoxig4aIh9KdlKI0c2jGJ9PVw0GqdnAJl/MzEcf1m3B+XJMQJa",
	"oN1djqapCOW3VYyA714R08PfD1bafkUaOzzTiN2ysvGEHla26aUDzovHWKDYPGDgfhXN/eiNwfKQVPz4",
	"CFKD/QKE7i/FpKzdJmsVoLLSoR8jotSVDgM6clwrHlJezOfTSaU+6opM4GLOf2oT/xwbJo5h9mF2TwN3",
	"orAvTSoSIsK2tfrQ4AIUZKWmxBehgw7tGpQmT5cCkEcSjD0pLSUQwD2jdWwMjoZw6WOecrN3e6vUT+bz",
	"E2vUD1uf7tbdRhaoTy68fYml6enkqfAy9kbLc7fjTc9fPPD5Hx70/LMH0dMr7zmxd4X9r+9IbXG7I8KB",
	"oQy5iWbH5hfcvyaMJFtqdr2/Eu57e+yE7TTDOdt2tqV/yXMEejs6HpDjRLuvGB+m9j0d8mQ+53UirjH6",
	"tYUOHss1gzIVS1TCZNHS1arkhqgK7Yva5PpG540q4+5ZrvNFbz4b23VpwVN7uMY6xI7TGafwdmYwOlDu",
	"lXjkdgaWaZ1sSRCha3NVioOmE/fOna0lGBa2TCuAjKAJMaya9ZqFGDFeXJbj6kyKi6rxgatuh4HqTEi3",
	"tiPjIQKUHcUWA0Z5/sXmuwd5rzX4y5qt604/lg8OKPrda/40eGdv+vTudthdC67B268YhwYLnUe+5RCN",
	"kSHUzmbo/eEHHdv+eIIwvATeP0isuviWsWrQu9sPV6KONlLdTtt+xqA5c9++Rm8a22v6DVDv99KlG1bH",
	"+8sA/TV0h5AVmF0PZ/+HRVh/yip++JVM+GAwffSTpBOj6S9lqRd/P1kvnOL5hG2df06mcnv+eWArtz2z",
	"Gyr8rzjQ97dS90NV/ftp+un86d+FZVyhyuOe4biIZOJ7om1y7+2do18VRUBeq1CMdjiG2e9BhfD9tn96",
	"3wHdTdjhmOq+1L2bTuKHiPsxWkTvD+KsXbNuTsfqqYwR+Zsx318YSl8s9FQrK1uSrduxwH12I1W3B6YC",
	"5BZ9HKjze/wxYw8UpqpLPljzhwnhVXMYHx4Hy06HhpEN1W8MqO4Xngbbdz6K39htT3f/f2u9b4u3TsXC",
	"uJes9kMg5UaZmH06gbTk475tgbGrjwkfgy9sU+a8YAKuMYZnPpfyNbSXplL3OSi3wTOEQnlYIRpojNy9",
	"Y/elcJqGBlwgWbPWm0ZWLhz6wpZpnVkFUNIk57ZJ+ymTbYJMDGVRLbnroZv+FHm+0z8Cfgzndan0nmd0",
	"HzHY65Hm1ag3JP55dU7ffMEk/eyBhv/sQYZ8O0RcN2hI9TxhFQtKo+fzbiJyHgenvCA72oSQjw58fztD",
	"U1zmjsLIpxMypYoDxLgguDeFoQjdzfSyFO3zXsuNRy7JFFQJm0Y5ZQJSPi90nP/m6Ljh5uzWL7reg9qf",
	"+PB0TtqiiXbNqQO91P2ZMqkTzd07KiMOjTF+MfGqPfyrZY3BlzDfPF/0vws5mjDko5C1NtoXf6jc8I1r",
	"68EGyWHAFzEO/UOclaHTw6J9ClxkztxFo9i7XuusF+u3BcGlwYel2kNjHKqsSE08nRUQ1HVEc7XNU/va",
	"2aDavc443qIQLiPtMZdhJn6v8C3wM9g9afwR4zlJUg8C+u3t/wUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
